#!/bin/bash

CLANG_FORMAT=clang-format
CLANG_TIDY=clang-tidy
CACHE_FILE=".clang-tidy-cache"

if ! command -v "$CLANG_FORMAT" &> /dev/null; then
  echo "clang-format not found"
  exit 1
fi
if ! command -v "$CLANG_TIDY" > /dev/null; then
  echo "clang-tidy not found"
  exit 1
fi

EXTENSIONS="h cpp cc cxx c hpp"
FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -Ev "test|NewOroFix44_|fix_[app|wrapper]" | grep -E "\.(${EXTENSIONS// /|})$")

if [ -z "$FILES" ]; then
  exit 0
fi

[ -e "$CACHE_FILE" ] || touch "$CACHE_FILE"

if [ ! -e build/compile_commands.json ]; then
  echo "build/compile_commands.json not found, running cmake..."
  cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON || exit 1
fi

FAIL=0
for file in $FILES; do
  HASH=$(git hash-object "$file")
  CACHED=$(grep "$file $HASH" "$CACHE_FILE")

  echo "• $file"
  $CLANG_FORMAT -i "$file"
  git add "$file"
  echo "formatted: $file"

  if [ -n "$CACHED" ]; then
    echo "skipped clang-tidy (cached): $file"
    continue
  fi

  "$CLANG_TIDY" "$file" -p build
  if [ $? -ne 0 ]; then
    echo "clang-tidy found issues in $file"
    FAIL=1
    break
  else
    # update cache
    grep -v "^$file " "$CACHE_FILE" > "$CACHE_FILE.tmp"
    echo "$file $HASH" >> "$CACHE_FILE.tmp"
    mv "$CACHE_FILE.tmp" "$CACHE_FILE"
  fi
done

if [ "$FAIL" -ne 0 ]; then
  echo "Commit blocked due to clang-tidy errors."
  exit 1
fi

exit 0
