#!/bin/bash

CLANG_FORMAT=clang-format
CLANG_TIDY=clang-tidy
CACHE_FILE=".clang-tidy-cache"
BUILD_DIR="build"

OS_NAME=$(uname)

if ! command -v "$CLANG_FORMAT" &> /dev/null; then
  echo "clang-format not found"
  exit 1
fi
if ! command -v "$CLANG_TIDY" > /dev/null; then
  echo "clang-tidy not found"
  exit 1
fi

EXTENSIONS="cpp cc cxx c h hpp tpp"
FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -Ev "test|NewOroFix44MD_|NewOroFix44OE_|fix_[?:app|md_app|oe_app]|fix_*_[core]|schema|pch\.h" | grep -E "\.(${EXTENSIONS// /|})$")

HEADERS=$(git diff --cached --name-only --diff-filter=ACM | grep -Ev "test|schema|pch\.h" | grep -E "\.(h|hpp)$")
CHECK_MAIN=0
if [ -n "$HEADERS" ]; then
  CHECK_MAIN=1
  FILES=$(echo "$FILES" | grep -v "^main.cpp$")
fi

if [ -z "$FILES" ] && [ "$CHECK_MAIN" -eq 0 ]; then
  exit 0
fi

[ -e "$CACHE_FILE" ] || touch "$CACHE_FILE"

if [ ! -e "${BUILD_DIR}/compile_commands.json" ]; then
  echo "${BUILD_DIR}/compile_commands.json not found, running cmake..."

  if [[ "${OS_NAME}" == "Darwin" ]]; then
    SDK_PATH=$(xcrun --show-sdk-path)
    echo "Detected macOS SDK: $SDK_PATH"

    cmake -S . -B ${BUILD_DIR} \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DENABLE_WEBSOCKET=ON \
    -DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON \
    -DCMAKE_CXX_STANDARD=20 \
    -DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm/bin/clang \
    -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++ \
    -DCMAKE_OSX_SYSROOT="$SDK_PATH" \
    -DCMAKE_OSX_DEPLOYMENT_TARGET=13.3
    cmake --build ${BUILD_DIR} --target websockets || exit 1
  elif [[ "${OS_NAME}" == "Linux" ]]; then
    cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_WEBSOCKET=ON -DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON ; cmake --build ${BUILD_DIR} --target websockets || exit 1
  fi

fi

FAIL=0
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
for file in $FILES; do
  echo "• $file"
  $CLANG_FORMAT -i "$file"
  git add "$file"
  echo "formatted: $file"

  if [[ "$file" == *.h || "$file" == *.hpp ]]; then
    continue
  fi

  HASH=$(git hash-object "$file")
  CACHED=$(grep "$file $HASH" "$CACHE_FILE")

  if [ -n "$CACHED" ]; then
    echo "skipped clang-tidy (cached): $file"
    continue
  fi

  if [[ "${OS_NAME}" == "Darwin" ]]; then
    "$CLANG_TIDY" "$file" -p "$BUILD_DIR" --extra-arg="-include" --extra-arg="${SCRIPT_DIR}/include/pch.h"
  elif [[ "${OS_NAME}" == "Linux" ]]; then
    "$CLANG_TIDY" "$file" -p "$BUILD_DIR"
  fi

  if [ $? -ne 0 ]; then
    echo "clang-tidy found issues in $file"
    FAIL=1
    break
  else
    # update cache
    grep -v "^$file " "$CACHE_FILE" > "$CACHE_FILE.tmp"
    echo "$file $HASH" >> "$CACHE_FILE.tmp"
    mv "$CACHE_FILE.tmp" "$CACHE_FILE"
  fi
done

if [ "$FAIL" -ne 0 ]; then
  echo "Commit blocked due to clang-tidy errors."
  exit 1
fi

if [ "$CHECK_MAIN" -eq 1 ]; then
  echo "• main.cpp (header changes detected)"
  $CLANG_FORMAT -i "main.cpp"
  git add "main.cpp"
  echo "formatted: main.cpp"

  if [[ "${OS_NAME}" == "Darwin" ]]; then
    "$CLANG_TIDY" "main.cpp" -p "$BUILD_DIR" --extra-arg="-include" --extra-arg="${SCRIPT_DIR}/include/pch.h"
  elif [[ "${OS_NAME}" == "Linux" ]]; then
    "$CLANG_TIDY" "main.cpp" -p "$BUILD_DIR"
  fi

  if [ $? -ne 0 ]; then
    echo "clang-tidy found issues in main.cpp (triggered by header changes)"
    exit 1
  fi
fi

exit 0
