#!/bin/bash

CLANG_FORMAT=clang-format
CLANG_TIDY=clang-tidy

if ! command -v "$CLANG_FORMAT" &> /dev/null; then
  echo "clang format not found"
  exit 1
fi
if ! command -v "$CLANG_TIDY" > /dev/null; then
  echo "clang-tidy not found"
  exit 1
fi

EXTENSIONS="h cpp cc cxx c"

FILES=$(git diff --cached --name-only --diff-filter=ACM |grep -v "test" |grep -E "\.(${EXTENSIONS// /|})$")

if [ -z "$FILES" ]; then
  exit 0
fi

COMPILER_FLAGS=(-xc++ -std=c++20 -I./include -I./hft -include include/pch.h)

FAIL=0
for file in $FILES; do
  echo "  • $file"
  $CLANG_FORMAT -i "$file"
  git add "$file"
  echo "formatted: $file"

  if [ ! -e build/compile_commands.json ]; then
    echo "make build folder and run cmake"
    cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
  fi

  "$CLANG_TIDY" "$file" -p build
  if [ $? -ne 0 ]; then
      echo "clang-tidy found issues in $file"
      FAIL=1
      break
    fi
done

if [ "$FAIL" -ne 0 ]; then
  echo "Commit blocked due to clang-tidy errors."
  exit 1
fi

exit 0

