//-------------------------------------------------------------------------------------------------
// *** f8c generated file: DO NOT EDIT! Created: 2025-07-17 17:44:16 ***
//-------------------------------------------------------------------------------------------------
/*

Fix8 is released under the GNU LESSER GENERAL PUBLIC LICENSE Version 3.

Fix8 Open Source FIX Engine.
Copyright (C) 2010-25 David L. Dight <fix@fix8.org>

Fix8 is free software: you can  redistribute it and / or modify  it under the  terms of the
GNU Lesser General  Public License as  published  by the Free  Software Foundation,  either
version 3 of the License, or (at your option) any later version.

Fix8 is distributed in the hope  that it will be useful, but WITHOUT ANY WARRANTY;  without
even the  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

You should  have received a copy of the GNU Lesser General Public  License along with Fix8.
If not, see <http://www.gnu.org/licenses/>.

*******************************************************************************************
*                Special note for Fix8 compiler generated source code                     *
*                                                                                         *
* Binary works  that are the results of compilation of code that is generated by the Fix8 *
* compiler  can be released  without releasing your  source code as  long as your  binary *
* links dynamically  against an  unmodified version of the Fix8 library.  You are however *
* required to leave the copyright text in the generated code.                             *
*                                                                                         *
*******************************************************************************************

BECAUSE THE PROGRAM IS  LICENSED FREE OF  CHARGE, THERE IS NO  WARRANTY FOR THE PROGRAM, TO
THE EXTENT  PERMITTED  BY  APPLICABLE  LAW.  EXCEPT WHEN  OTHERWISE  STATED IN  WRITING THE
COPYRIGHT HOLDERS AND/OR OTHER PARTIES  PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY OF ANY
KIND,  EITHER EXPRESSED   OR   IMPLIED,  INCLUDING,  BUT   NOT  LIMITED   TO,  THE  IMPLIED
WARRANTIES  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS TO
THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE,
YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

IN NO EVENT UNLESS REQUIRED  BY APPLICABLE LAW  OR AGREED TO IN  WRITING WILL ANY COPYRIGHT
HOLDER, OR  ANY OTHER PARTY  WHO MAY MODIFY  AND/OR REDISTRIBUTE  THE PROGRAM AS  PERMITTED
ABOVE,  BE  LIABLE  TO  YOU  FOR  DAMAGES,  INCLUDING  ANY  GENERAL, SPECIAL, INCIDENTAL OR
CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT
NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR
THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH
HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

*/

//-------------------------------------------------------------------------------------------------
#include <fix8/f8config.h>
#if defined FIX8_MAGIC_NUM && FIX8_MAGIC_NUM > 16793603L
#error NewOroFix44_classes.hpp version 1.4.3 is out of date. Please regenerate with f8c.
#endif
//-------------------------------------------------------------------------------------------------
// NewOroFix44_classes.hpp
//-------------------------------------------------------------------------------------------------
#ifndef FIX8_4E65774F726F46697834345F636C61737365732E687070_
#define FIX8_4E65774F726F46697834345F636C61737365732E687070_

#if defined(_MSC_VER) && defined(F8_NewOroFix44_API_SHARED)
    #if defined(BUILD_F8_NewOroFix44_API)
        #define F8_NewOroFix44_API __declspec(dllexport)
    #else
        #define F8_NewOroFix44_API __declspec(dllimport)
    #endif
#else
    #define F8_NewOroFix44_API
#endif
namespace FIX8 {

extern "C"
{
   F8_NewOroFix44_API const F8MetaCntx& NewOroFix44_ctx();
}

namespace NewOroFix44 {

//-------------------------------------------------------------------------------------------------
using NewOroFix44_BaseMsgEntry = MsgTable;
/// Compiler generated metadata object, accessed through this function.
F8_NewOroFix44_API const F8MetaCntx& ctx();
class NewOroFix44_Router;

//-------------------------------------------------------------------------------------------------
/// Heartbeat (0), admin, 1 field, 0 groups.
class Heartbeat : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 1;

public:
   explicit Heartbeat(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha) {}
   ~Heartbeat() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }
   bool is_admin() const { return true; }

   static const MsgType& get_msgtype() { return _msgtype; }
};

//-------------------------------------------------------------------------------------------------
/// TestRequest (1), admin, 1 field, 0 groups.
class TestRequest : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 1;

public:
   explicit TestRequest(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha) {}
   ~TestRequest() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }
   bool is_admin() const { return true; }

   static const MsgType& get_msgtype() { return _msgtype; }
};

//-------------------------------------------------------------------------------------------------
/// Reject (3), admin, 6 fields, 0 groups.
class Reject : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 6;

public:
   explicit Reject(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha) {}
   ~Reject() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }
   bool is_admin() const { return true; }

   static const MsgType& get_msgtype() { return _msgtype; }
};

//-------------------------------------------------------------------------------------------------
/// Logout (5), admin, 1 field, 0 groups.
class Logout : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 1;

public:
   explicit Logout(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha) {}
   ~Logout() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }
   bool is_admin() const { return true; }

   static const MsgType& get_msgtype() { return _msgtype; }
};

//-------------------------------------------------------------------------------------------------
/// ExecutionReport (8), application, 53 fields, 1 group.
class ExecutionReport : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 53;

public:
   explicit ExecutionReport(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha)
   {
      if (deepctor)
         _groups.insert({136, new NoMiscFees });
   }
   ~ExecutionReport() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }

   static const MsgType& get_msgtype() { return _msgtype; }
   GroupBase *create_nested_group(unsigned short fnum) const
      { return fnum == 136 ? new NoMiscFees : nullptr; }

   /// NoMiscFees (136), application, 3 fields, 0 groups, is unique, hash: 0x8b704e43
   // ExecutionReport::NoMiscFees
   class NoMiscFees : public GroupBase // depth: 1
   {
      static F8_NewOroFix44_API const FieldTrait _traits[];
      static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha;
      static F8_NewOroFix44_API const MsgType _msgtype;
      static const unsigned _fieldcnt = 3;

   public:
      enum { _fnum = 136 };

      NoMiscFees() : GroupBase(_fnum) {}
      ~NoMiscFees() = default;
      MessageBase *create_group(bool) const { return new MessageBase(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha); }

      static const MsgType& get_msgtype() { return _msgtype; }
   };
};

//-------------------------------------------------------------------------------------------------
/// OrderCancelReject (9), application, 10 fields, 0 groups.
class OrderCancelReject : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 10;

public:
   explicit OrderCancelReject(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha) {}
   ~OrderCancelReject() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }

   static const MsgType& get_msgtype() { return _msgtype; }
};

//-------------------------------------------------------------------------------------------------
/// Logon (A), admin, 10 fields, 0 groups.
class Logon : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 10;

public:
   explicit Logon(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha) {}
   ~Logon() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }
   bool is_admin() const { return true; }

   static const MsgType& get_msgtype() { return _msgtype; }
};

//-------------------------------------------------------------------------------------------------
/// News (B), application, 1 field, 0 groups.
class News : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 1;

public:
   explicit News(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha) {}
   ~News() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }

   static const MsgType& get_msgtype() { return _msgtype; }
};

//-------------------------------------------------------------------------------------------------
/// NewOrderSingle (D), application, 20 fields, 0 groups.
class NewOrderSingle : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 20;

public:
   explicit NewOrderSingle(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha) {}
   ~NewOrderSingle() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }

   static const MsgType& get_msgtype() { return _msgtype; }
};

//-------------------------------------------------------------------------------------------------
/// NewOrderList (E), application, 3 fields, 1 group.
class NewOrderList : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 3;

public:
   explicit NewOrderList(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha)
   {
      if (deepctor)
         _groups.insert({73, new NoOrders });
   }
   ~NewOrderList() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }

   static const MsgType& get_msgtype() { return _msgtype; }
   GroupBase *create_nested_group(unsigned short fnum) const
      { return fnum == 73 ? new NoOrders : nullptr; }

   /// NoOrders (73), application, 20 fields, 1 group, is unique, hash: 0x13d63e62
   // NewOrderList::NoOrders
   class NoOrders : public GroupBase // depth: 1
   {
      static F8_NewOroFix44_API const FieldTrait _traits[];
      static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha;
      static F8_NewOroFix44_API const MsgType _msgtype;
      static const unsigned _fieldcnt = 20;

   public:
      enum { _fnum = 73 };

      NoOrders() : GroupBase(_fnum) {}
      ~NoOrders() = default;
      MessageBase *create_group(bool deepctor) const
      {
         MessageBase *mb(new MessageBase(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha));
         if (deepctor)
            mb->get_groups().insert({25010, new NoListTriggeringInstructions });
         return mb;
      }

      static const MsgType& get_msgtype() { return _msgtype; }

      GroupBase *create_nested_group(unsigned short fnum) const
         { return fnum == 25010 ? new NoListTriggeringInstructions : nullptr; }

      /// NoListTriggeringInstructions (25010), application, 3 fields, 0 groups, shares static data, hash: 0x6edf2ef5
      // NewOrderList::NoOrders::NoListTriggeringInstructions
      class NoListTriggeringInstructions : public GroupBase // depth: 2
      {
         static F8_NewOroFix44_API const FieldTrait *_traits;
         static F8_NewOroFix44_API const FieldTrait_Hash_Array& _ftha;
         static F8_NewOroFix44_API const MsgType& _msgtype;
         static const unsigned _fieldcnt = 3;

      public:
         enum { _fnum = 25010 };

         NoListTriggeringInstructions() : GroupBase(_fnum) {}
         ~NoListTriggeringInstructions() = default;
         MessageBase *create_group(bool) const { return new MessageBase(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha); }

         static const MsgType& get_msgtype() { return _msgtype; }
      };
   };
};

//-------------------------------------------------------------------------------------------------
/// OrderCancelRequest (F), application, 7 fields, 0 groups.
class OrderCancelRequest : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 7;

public:
   explicit OrderCancelRequest(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha) {}
   ~OrderCancelRequest() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }

   static const MsgType& get_msgtype() { return _msgtype; }
};

//-------------------------------------------------------------------------------------------------
/// ListStatus (N), application, 10 fields, 1 group.
class ListStatus : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 10;

public:
   explicit ListStatus(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha)
   {
      if (deepctor)
         _groups.insert({73, new NoOrders });
   }
   ~ListStatus() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }

   static const MsgType& get_msgtype() { return _msgtype; }
   GroupBase *create_nested_group(unsigned short fnum) const
      { return fnum == 73 ? new NoOrders : nullptr; }

   /// NoOrders (73), application, 7 fields, 1 group, is unique, hash: 0x528555ff
   // ListStatus::NoOrders
   class NoOrders : public GroupBase // depth: 1
   {
      static F8_NewOroFix44_API const FieldTrait _traits[];
      static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha;
      static F8_NewOroFix44_API const MsgType _msgtype;
      static const unsigned _fieldcnt = 7;

   public:
      enum { _fnum = 73 };

      NoOrders() : GroupBase(_fnum) {}
      ~NoOrders() = default;
      MessageBase *create_group(bool deepctor) const
      {
         MessageBase *mb(new MessageBase(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha));
         if (deepctor)
            mb->get_groups().insert({25010, new NoListTriggeringInstructions });
         return mb;
      }

      static const MsgType& get_msgtype() { return _msgtype; }

      GroupBase *create_nested_group(unsigned short fnum) const
         { return fnum == 25010 ? new NoListTriggeringInstructions : nullptr; }

      /// NoListTriggeringInstructions (25010), application, 3 fields, 0 groups, shares static data, hash: 0x6edf2ef5
      // ListStatus::NoOrders::NoListTriggeringInstructions
      class NoListTriggeringInstructions : public GroupBase // depth: 2
      {
         static F8_NewOroFix44_API const FieldTrait *_traits;
         static F8_NewOroFix44_API const FieldTrait_Hash_Array& _ftha;
         static F8_NewOroFix44_API const MsgType& _msgtype;
         static const unsigned _fieldcnt = 3;

      public:
         enum { _fnum = 25010 };

         NoListTriggeringInstructions() : GroupBase(_fnum) {}
         ~NoListTriggeringInstructions() = default;
         MessageBase *create_group(bool) const { return new MessageBase(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha); }

         static const MsgType& get_msgtype() { return _msgtype; }
      };
   };
};

//-------------------------------------------------------------------------------------------------
/// MarketDataRequest (V), application, 6 fields, 2 groups.
class MarketDataRequest : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 6;

public:
   explicit MarketDataRequest(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha)
   {
      if (deepctor)
         _groups.insert({
            { 146, new NoRelatedSym },
            { 267, new NoMDEntryTypes },
         });
   }
   ~MarketDataRequest() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }

   static const MsgType& get_msgtype() { return _msgtype; }
   GroupBase *create_nested_group(unsigned short fnum) const
   {
      switch(fnum)
      {
      case 146: return new NoRelatedSym;
      case 267: return new NoMDEntryTypes;
      default: return nullptr;
      }
   }

   /// NoRelatedSym (146), application, 1 field, 0 groups, is unique, hash: 0x80001836
   // MarketDataRequest::NoRelatedSym
   class NoRelatedSym : public GroupBase // depth: 1
   {
      static F8_NewOroFix44_API const FieldTrait _traits[];
      static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha;
      static F8_NewOroFix44_API const MsgType _msgtype;
      static const unsigned _fieldcnt = 1;

   public:
      enum { _fnum = 146 };

      NoRelatedSym() : GroupBase(_fnum) {}
      ~NoRelatedSym() = default;
      MessageBase *create_group(bool) const { return new MessageBase(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha); }

      static const MsgType& get_msgtype() { return _msgtype; }
   };

   /// NoMDEntryTypes (267), application, 1 field, 0 groups, is unique, hash: 0x8000190c
   // MarketDataRequest::NoMDEntryTypes
   class NoMDEntryTypes : public GroupBase // depth: 1
   {
      static F8_NewOroFix44_API const FieldTrait _traits[];
      static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha;
      static F8_NewOroFix44_API const MsgType _msgtype;
      static const unsigned _fieldcnt = 1;

   public:
      enum { _fnum = 267 };

      NoMDEntryTypes() : GroupBase(_fnum) {}
      ~NoMDEntryTypes() = default;
      MessageBase *create_group(bool) const { return new MessageBase(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha); }

      static const MsgType& get_msgtype() { return _msgtype; }
   };
};

//-------------------------------------------------------------------------------------------------
/// MarketDataSnapshot (W), application, 4 fields, 1 group.
class MarketDataSnapshot : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 4;

public:
   explicit MarketDataSnapshot(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha)
   {
      if (deepctor)
         _groups.insert({268, new NoMDEntries });
   }
   ~MarketDataSnapshot() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }

   static const MsgType& get_msgtype() { return _msgtype; }
   GroupBase *create_nested_group(unsigned short fnum) const
      { return fnum == 268 ? new NoMDEntries : nullptr; }

   /// NoMDEntries (268), application, 3 fields, 0 groups, is unique, hash: 0x9b46ef3e
   // MarketDataSnapshot::NoMDEntries
   class NoMDEntries : public GroupBase // depth: 1
   {
      static F8_NewOroFix44_API const FieldTrait _traits[];
      static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha;
      static F8_NewOroFix44_API const MsgType _msgtype;
      static const unsigned _fieldcnt = 3;

   public:
      enum { _fnum = 268 };

      NoMDEntries() : GroupBase(_fnum) {}
      ~NoMDEntries() = default;
      MessageBase *create_group(bool) const { return new MessageBase(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha); }

      static const MsgType& get_msgtype() { return _msgtype; }
   };
};

//-------------------------------------------------------------------------------------------------
/// MarketDataIncrementalRefresh (X), application, 3 fields, 1 group.
class MarketDataIncrementalRefresh : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 3;

public:
   explicit MarketDataIncrementalRefresh(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha)
   {
      if (deepctor)
         _groups.insert({268, new NoMDEntries });
   }
   ~MarketDataIncrementalRefresh() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }

   static const MsgType& get_msgtype() { return _msgtype; }
   GroupBase *create_nested_group(unsigned short fnum) const
      { return fnum == 268 ? new NoMDEntries : nullptr; }

   /// NoMDEntries (268), application, 10 fields, 0 groups, is unique, hash: 0xca4606b6
   // MarketDataIncrementalRefresh::NoMDEntries
   class NoMDEntries : public GroupBase // depth: 1
   {
      static F8_NewOroFix44_API const FieldTrait _traits[];
      static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha;
      static F8_NewOroFix44_API const MsgType _msgtype;
      static const unsigned _fieldcnt = 10;

   public:
      enum { _fnum = 268 };

      NoMDEntries() : GroupBase(_fnum) {}
      ~NoMDEntries() = default;
      MessageBase *create_group(bool) const { return new MessageBase(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha); }

      static const MsgType& get_msgtype() { return _msgtype; }
   };
};

//-------------------------------------------------------------------------------------------------
/// OrderAmendKeepPriorityRequest (XAK), application, 5 fields, 0 groups.
class OrderAmendKeepPriorityRequest : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 5;

public:
   explicit OrderAmendKeepPriorityRequest(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha) {}
   ~OrderAmendKeepPriorityRequest() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }

   static const MsgType& get_msgtype() { return _msgtype; }
};

//-------------------------------------------------------------------------------------------------
/// OrderAmendReject (XAR), application, 7 fields, 0 groups.
class OrderAmendReject : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 7;

public:
   explicit OrderAmendReject(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha) {}
   ~OrderAmendReject() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }

   static const MsgType& get_msgtype() { return _msgtype; }
};

//-------------------------------------------------------------------------------------------------
/// OrderCancelRequestAndNewOrderSingle (XCN), application, 25 fields, 0 groups.
class OrderCancelRequestAndNewOrderSingle : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 25;

public:
   explicit OrderCancelRequestAndNewOrderSingle(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha) {}
   ~OrderCancelRequestAndNewOrderSingle() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }

   static const MsgType& get_msgtype() { return _msgtype; }
};

//-------------------------------------------------------------------------------------------------
/// LimitQuery (XLQ), application, 1 field, 0 groups.
class LimitQuery : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 1;

public:
   explicit LimitQuery(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha) {}
   ~LimitQuery() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }

   static const MsgType& get_msgtype() { return _msgtype; }
};

//-------------------------------------------------------------------------------------------------
/// LimitResponse (XLR), application, 2 fields, 1 group.
class LimitResponse : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 2;

public:
   explicit LimitResponse(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha)
   {
      if (deepctor)
         _groups.insert({25003, new NoLimitIndicators });
   }
   ~LimitResponse() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }

   static const MsgType& get_msgtype() { return _msgtype; }
   GroupBase *create_nested_group(unsigned short fnum) const
      { return fnum == 25003 ? new NoLimitIndicators : nullptr; }

   /// NoLimitIndicators (25003), application, 5 fields, 0 groups, is unique, hash: 0x516c00e6
   // LimitResponse::NoLimitIndicators
   class NoLimitIndicators : public GroupBase // depth: 1
   {
      static F8_NewOroFix44_API const FieldTrait _traits[];
      static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha;
      static F8_NewOroFix44_API const MsgType _msgtype;
      static const unsigned _fieldcnt = 5;

   public:
      enum { _fnum = 25003 };

      NoLimitIndicators() : GroupBase(_fnum) {}
      ~NoLimitIndicators() = default;
      MessageBase *create_group(bool) const { return new MessageBase(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha); }

      static const MsgType& get_msgtype() { return _msgtype; }
   };
};

//-------------------------------------------------------------------------------------------------
/// MarketDataRequestReject (Y), application, 4 fields, 0 groups.
class MarketDataRequestReject : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 4;

public:
   explicit MarketDataRequestReject(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha) {}
   ~MarketDataRequestReject() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }

   static const MsgType& get_msgtype() { return _msgtype; }
};

//-------------------------------------------------------------------------------------------------
/// header (header), application, 8 fields, 0 groups.
class header : public MessageBase
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 8;

   begin_string *_begin_string;
   body_length *_body_length;
   msg_type *_msg_type;

public:
   explicit header(bool deepctor=true) : MessageBase(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha),
      _begin_string(new begin_string(ctx()._beginStr)), _body_length(new body_length), _msg_type(new msg_type) { add_preamble(); }
   ~header() = default;

   static const MsgType& get_msgtype() { return _msgtype; }

	begin_string *get_begin_string() { return _begin_string; };
	body_length *get_body_length() { return _body_length; };
	msg_type *get_msg_type() { return _msg_type; };

	void add_preamble()
	{
		add_field(Common_BeginString, 1, _begin_string, false);
		add_field(Common_BodyLength, 2, _body_length, false);
		add_field(Common_MsgType, 3, _msg_type, false);
	}
};

//-------------------------------------------------------------------------------------------------
/// OrderMassCancelRequest (q), application, 3 fields, 0 groups.
class OrderMassCancelRequest : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 3;

public:
   explicit OrderMassCancelRequest(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha) {}
   ~OrderMassCancelRequest() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }

   static const MsgType& get_msgtype() { return _msgtype; }
};

//-------------------------------------------------------------------------------------------------
/// OrderMassCancelReport (r), application, 8 fields, 0 groups.
class OrderMassCancelReport : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 8;

public:
   explicit OrderMassCancelReport(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha) {}
   ~OrderMassCancelReport() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }

   static const MsgType& get_msgtype() { return _msgtype; }
};

//-------------------------------------------------------------------------------------------------
/// trailer (trailer), application, 1 field, 0 groups.
class trailer : public MessageBase
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 1;

   check_sum *_check_sum;

public:
   explicit trailer(bool deepctor=true) : MessageBase(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha),
      _check_sum(new check_sum) { add_preamble(); }
   ~trailer() = default;

   static const MsgType& get_msgtype() { return _msgtype; }

	check_sum *get_check_sum() { return _check_sum; };

	void add_preamble()
	{
		add_field(Common_CheckSum, 3, _check_sum, false);
	}
};

//-------------------------------------------------------------------------------------------------
/// InstrumentListRequest (x), application, 3 fields, 0 groups.
class InstrumentListRequest : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 3;

public:
   explicit InstrumentListRequest(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha) {}
   ~InstrumentListRequest() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }

   static const MsgType& get_msgtype() { return _msgtype; }
};

//-------------------------------------------------------------------------------------------------
/// InstrumentList (y), application, 2 fields, 1 group.
class InstrumentList : public Message
{
   static F8_NewOroFix44_API const FieldTrait _traits[];
   static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha; 
   static F8_NewOroFix44_API const MsgType _msgtype;
   static F8_NewOroFix44_API const unsigned _fieldcnt = 2;

public:
   explicit InstrumentList(bool deepctor=true) : Message(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha)
   {
      if (deepctor)
         _groups.insert({146, new NoRelatedSym });
   }
   ~InstrumentList() = default;
   bool process(Router& rt) const { return (static_cast<NewOroFix44_Router&>(rt))(this); }

   static const MsgType& get_msgtype() { return _msgtype; }
   GroupBase *create_nested_group(unsigned short fnum) const
      { return fnum == 146 ? new NoRelatedSym : nullptr; }

   /// NoRelatedSym (146), application, 9 fields, 0 groups, is unique, hash: 0xa7bc7e19
   // InstrumentList::NoRelatedSym
   class NoRelatedSym : public GroupBase // depth: 1
   {
      static F8_NewOroFix44_API const FieldTrait _traits[];
      static F8_NewOroFix44_API const FieldTrait_Hash_Array _ftha;
      static F8_NewOroFix44_API const MsgType _msgtype;
      static const unsigned _fieldcnt = 9;

   public:
      enum { _fnum = 146 };

      NoRelatedSym() : GroupBase(_fnum) {}
      ~NoRelatedSym() = default;
      MessageBase *create_group(bool) const { return new MessageBase(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha); }

      static const MsgType& get_msgtype() { return _msgtype; }
   };
};

//-------------------------------------------------------------------------------------------------

} // namespace NewOroFix44
} // namespace FIX8
#endif // FIX8_4E65774F726F46697834345F636C61737365732E687070_
