//-------------------------------------------------------------------------------------------------
// *** f8c generated file: DO NOT EDIT! Created: 2025-07-26 15:49:19 ***
//-------------------------------------------------------------------------------------------------
/*

Fix8 is released under the GNU LESSER GENERAL PUBLIC LICENSE Version 3.

Fix8 Open Source FIX Engine.
Copyright (C) 2010-25 David L. Dight <fix@fix8.org>

Fix8 is free software: you can  redistribute it and / or modify  it under the  terms of the
GNU Lesser General  Public License as  published  by the Free  Software Foundation,  either
version 3 of the License, or (at your option) any later version.

Fix8 is distributed in the hope  that it will be useful, but WITHOUT ANY WARRANTY;  without
even the  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

You should  have received a copy of the GNU Lesser General Public  License along with Fix8.
If not, see <http://www.gnu.org/licenses/>.

*******************************************************************************************
*                Special note for Fix8 compiler generated source code                     *
*                                                                                         *
* Binary works  that are the results of compilation of code that is generated by the Fix8 *
* compiler  can be released  without releasing your  source code as  long as your  binary *
* links dynamically  against an  unmodified version of the Fix8 library.  You are however *
* required to leave the copyright text in the generated code.                             *
*                                                                                         *
*******************************************************************************************

BECAUSE THE PROGRAM IS  LICENSED FREE OF  CHARGE, THERE IS NO  WARRANTY FOR THE PROGRAM, TO
THE EXTENT  PERMITTED  BY  APPLICABLE  LAW.  EXCEPT WHEN  OTHERWISE  STATED IN  WRITING THE
COPYRIGHT HOLDERS AND/OR OTHER PARTIES  PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY OF ANY
KIND,  EITHER EXPRESSED   OR   IMPLIED,  INCLUDING,  BUT   NOT  LIMITED   TO,  THE  IMPLIED
WARRANTIES  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS TO
THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE,
YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

IN NO EVENT UNLESS REQUIRED  BY APPLICABLE LAW  OR AGREED TO IN  WRITING WILL ANY COPYRIGHT
HOLDER, OR  ANY OTHER PARTY  WHO MAY MODIFY  AND/OR REDISTRIBUTE  THE PROGRAM AS  PERMITTED
ABOVE,  BE  LIABLE  TO  YOU  FOR  DAMAGES,  INCLUDING  ANY  GENERAL, SPECIAL, INCIDENTAL OR
CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT
NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR
THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH
HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

*/

//-------------------------------------------------------------------------------------------------
#include <fix8/f8config.h>
#if defined FIX8_MAGIC_NUM && FIX8_MAGIC_NUM > 16793603L
#error NewOroFix44OE_traits.cpp version 1.4.3 is out of date. Please regenerate with f8c.
#endif
//-------------------------------------------------------------------------------------------------
// NewOroFix44OE_traits.cpp
//-------------------------------------------------------------------------------------------------
#include <iostream>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <vector>
#include <map>
#include <list>
#include <set>
#include <iterator>
#include <algorithm>
#include <cerrno>
#include <string.h>
// f8 includes
#include <fix8/f8exception.hpp>
#include <fix8/hypersleep.hpp>
#include <fix8/mpmc.hpp>
#include <fix8/thread.hpp>
#include <fix8/f8types.hpp>
#include <fix8/f8utils.hpp>
#include <fix8/tickval.hpp>
#include <fix8/logger.hpp>
#include <fix8/traits.hpp>
#include <fix8/field.hpp>
#include <fix8/message.hpp>
#include "NewOroFix44OE_types.hpp"
#include "NewOroFix44OE_router.hpp"
#include "NewOroFix44OE_classes.hpp"
//-------------------------------------------------------------------------------------------------
namespace FIX8 {
namespace NewOroFix44OE {

//-------------------------------------------------------------------------------------------------
// Common group traits
namespace {
//-------------------------------------------------------------------------------------------------
const FieldTrait NoListTriggeringInstructionsV1_traits[] // refs:2
{
   {25011, 7,  1,  0,0x04}, {25012, 1,  2,  0,0x04}, {25013, 7,  3,  0,0x04}
};
const FieldTrait_Hash_Array NoListTriggeringInstructionsV1_ftha(NoListTriggeringInstructionsV1_traits, 3);
const MsgType NoListTriggeringInstructionsV1_msgtype("NoListTriggeringInstructionsV1");
} // namespace

//-------------------------------------------------------------------------------------------------
// Message traits
//-------------------------------------------------------------------------------------------------
const FieldTrait Heartbeat::_traits[]
{
   { 112,15,  1,  0,0x04}
};
const FieldTrait_Hash_Array Heartbeat::_ftha(Heartbeat::_traits, Heartbeat::_fieldcnt);
const MsgType Heartbeat::_msgtype("0");
//-------------------------------------------------------------------------------------------------
const FieldTrait TestRequest::_traits[]
{
   { 112,15,  1,  0,0x05}
};
const FieldTrait_Hash_Array TestRequest::_ftha(TestRequest::_traits, TestRequest::_fieldcnt);
const MsgType TestRequest::_msgtype("1");
//-------------------------------------------------------------------------------------------------
const FieldTrait Reject::_traits[]
{
   {  45, 1,  1,  0,0x04}, {  58,15,  6,  0,0x04}, { 371, 1,  2,  0,0x04}, { 372,15,  3,  0,0x04},
   { 373, 1,  4,  0,0x04}, {25016, 1,  5,  0,0x04}
};
const FieldTrait_Hash_Array Reject::_ftha(Reject::_traits, Reject::_fieldcnt);
const MsgType Reject::_msgtype("3");
//-------------------------------------------------------------------------------------------------
const FieldTrait Logout::_traits[]
{
   {  58,15,  1,  0,0x04}
};
const FieldTrait_Hash_Array Logout::_ftha(Logout::_traits, Logout::_fieldcnt);
const MsgType Logout::_msgtype("5");
//-------------------------------------------------------------------------------------------------
const FieldTrait ExecutionReport::_traits[]
{
   {  11,15,  2,  0,0x04}, {  14,10, 27,  0,0x05}, {  17, 1,  1,  0,0x04}, {  18, 7,  9,  0,0x04},
   {  31,11, 32,  0,0x04}, {  32,10, 33,  0,0x05}, {  37, 1,  4,  0,0x04}, {  38,10,  5,  0,0x04},
   {  39, 7, 34,  0,0x05}, {  40, 7,  6,  0,0x05}, {  41,15,  3,  0,0x04}, {  44,11, 10,  0,0x04},
   {  54, 7,  7,  0,0x05}, {  55,15,  8,  0,0x05}, {  58,15, 53,  0,0x04}, {  59, 7, 17,  0,0x04},
   {  60,22, 18,  0,0x04}, {  66, 1, 21,  0,0x04}, {  70, 1, 35,  0,0x04}, { 103, 1, 51,  0,0x04},
   { 111,10, 20,  0,0x04}, { 136, 1, 50,  0,0x0c}, { 150, 7, 26,  0,0x05}, { 151,10, 28,  0,0x04},
   { 152,10, 22,  0,0x04}, { 574,15, 36,  0,0x04}, { 636, 8, 38,  0,0x04}, { 847, 1, 23,  0,0x04},
   {1003, 1, 31,  0,0x04}, {1057, 8, 30,  0,0x04}, {1100, 7, 11,  3,0x14}, {1101, 7, 12,  3,0x14},
   {1102,11, 13,  3,0x14}, {1107, 7, 14,  3,0x14}, {1109, 7, 15,  3,0x14}, {7940, 1, 24,  0,0x04},
   {25001, 7, 25,  0,0x04}, {25009, 1, 16,  3,0x14}, {25016, 1, 52,  0,0x04}, {25017,10, 29,  0,0x04},
   {25018,22, 19,  0,0x04}, {25021, 1, 37,  0,0x04}, {25022,22, 40,  0,0x04}, {25023,22, 39,  0,0x04},
   {25024, 1, 41,  0,0x04}, {25025,11, 42,  0,0x04}, {25026,10, 43,  0,0x04}, {25027, 1, 44,  0,0x04},
   {25028,15, 45,  0,0x04}, {25029, 1, 46,  0,0x04}, {25030,10, 47,  0,0x04}, {25031,10, 48,  0,0x04},
   {25032, 8, 49,  0,0x04}
};
const FieldTrait_Hash_Array ExecutionReport::_ftha(ExecutionReport::_traits, ExecutionReport::_fieldcnt);
const MsgType ExecutionReport::_msgtype("8");
//-------------------------------------------------------------------------------------------------
const FieldTrait ExecutionReport::NoMiscFees::_traits[]
{
   { 137,10,  1,  0,0x05}, { 138,15,  2,  0,0x05}, { 139, 1,  3,  0,0x05}
};
const FieldTrait_Hash_Array 
   ExecutionReport::NoMiscFees::_ftha(ExecutionReport::NoMiscFees::_traits, NoMiscFees::_fieldcnt);
const MsgType ExecutionReport::NoMiscFees::_msgtype("NoMiscFees");
//-------------------------------------------------------------------------------------------------
const FieldTrait OrderCancelReject::_traits[]
{
   {  11,15,  1,  0,0x05}, {  37, 1,  3,  0,0x04}, {  41,15,  2,  0,0x04}, {  55,15,  6,  0,0x05},
   {  58,15, 10,  0,0x05}, {  66, 1,  5,  0,0x04}, { 434, 7,  8,  0,0x05}, {25002, 1,  7,  0,0x04},
   {25015,15,  4,  0,0x04}, {25016, 1,  9,  0,0x05}
};
const FieldTrait_Hash_Array OrderCancelReject::_ftha(OrderCancelReject::_traits, OrderCancelReject::_fieldcnt);
const MsgType OrderCancelReject::_msgtype("9");
//-------------------------------------------------------------------------------------------------
const FieldTrait Logon::_traits[]
{
   {  95, 2,  3,  0,0x04}, {  96,28,  4,  0,0x04}, {  98, 1,  1,  0,0x04}, { 108, 1,  2,  0,0x05},
   { 141, 8,  5,  0,0x04}, { 553,15,  6,  0,0x04}, {9406, 8,  9,  0,0x04}, {25035, 1,  7,  0,0x04},
   {25036, 1,  8,  0,0x04}, {25037,15, 10,  0,0x04}
};
const FieldTrait_Hash_Array Logon::_ftha(Logon::_traits, Logon::_fieldcnt);
const MsgType Logon::_msgtype("A");
//-------------------------------------------------------------------------------------------------
const FieldTrait News::_traits[]
{
   { 148,15,  1,  0,0x05}
};
const FieldTrait_Hash_Array News::_ftha(News::_traits, News::_fieldcnt);
const MsgType News::_msgtype("B");
//-------------------------------------------------------------------------------------------------
const FieldTrait NewOrderSingle::_traits[]
{
   {  11,15,  1,  2,0x15}, {  18, 7,  4,  2,0x14}, {  38,10,  2,  2,0x14}, {  40, 7,  3,  2,0x15},
   {  44,11,  5,  2,0x14}, {  54, 7, 12,  2,0x15}, {  55,15, 13,  2,0x15}, {  59, 7, 14,  2,0x14},
   { 111,10, 15,  2,0x14}, { 152,10, 16,  2,0x14}, { 847, 1, 17,  2,0x14}, {1100, 7,  6,  3,0x14},
   {1101, 7,  7,  3,0x14}, {1102,11,  8,  3,0x14}, {1107, 7,  9,  3,0x14}, {1109, 7, 10,  3,0x14},
   {7940, 1, 18,  2,0x14}, {25001, 7, 19,  2,0x14}, {25009, 1, 11,  3,0x14}, {25032, 8, 20,  0,0x04}
};
const FieldTrait_Hash_Array NewOrderSingle::_ftha(NewOrderSingle::_traits, NewOrderSingle::_fieldcnt);
const MsgType NewOrderSingle::_msgtype("D");
//-------------------------------------------------------------------------------------------------
const FieldTrait NewOrderList::_traits[]
{
   {  73, 1,  3,  0,0x0c}, {1385, 1,  2,  0,0x05}, {25014,15,  1,  0,0x05}
};
const FieldTrait_Hash_Array NewOrderList::_ftha(NewOrderList::_traits, NewOrderList::_fieldcnt);
const MsgType NewOrderList::_msgtype("E");
//-------------------------------------------------------------------------------------------------
const FieldTrait NewOrderList::NoOrders::_traits[]
{
   {  11,15,  1,  2,0x15}, {  18, 7,  4,  2,0x14}, {  38,10,  2,  2,0x14}, {  40, 7,  3,  2,0x15},
   {  44,11,  5,  2,0x14}, {  54, 7, 12,  2,0x15}, {  55,15, 13,  2,0x15}, {  59, 7, 14,  2,0x14},
   { 111,10, 15,  2,0x14}, { 152,10, 16,  2,0x14}, { 847, 1, 17,  2,0x14}, {1100, 7,  6,  3,0x14},
   {1101, 7,  7,  3,0x14}, {1102,11,  8,  3,0x14}, {1107, 7,  9,  3,0x14}, {1109, 7, 10,  3,0x14},
   {7940, 1, 18,  2,0x14}, {25001, 7, 19,  2,0x14}, {25009, 1, 11,  3,0x14}, {25010, 1, 20,  1,0x1c}
};
const FieldTrait_Hash_Array 
   NewOrderList::NoOrders::_ftha(NewOrderList::NoOrders::_traits, NoOrders::_fieldcnt);
const MsgType NewOrderList::NoOrders::_msgtype("NoOrders");
//-------------------------------------------------------------------------------------------------
const FieldTrait *NewOrderList::NoOrders::NoListTriggeringInstructions::_traits(NoListTriggeringInstructionsV1_traits);
const FieldTrait_Hash_Array& NewOrderList::NoOrders::NoListTriggeringInstructions::_ftha(NoListTriggeringInstructionsV1_ftha);
const MsgType& NewOrderList::NoOrders::NoListTriggeringInstructions::_msgtype(NoListTriggeringInstructionsV1_msgtype);
//-------------------------------------------------------------------------------------------------
const FieldTrait OrderCancelRequest::_traits[]
{
   {  11,15,  1,  0,0x05}, {  37, 1,  3,  0,0x04}, {  41,15,  2,  0,0x04}, {  55,15,  6,  0,0x05},
   {  66, 1,  5,  0,0x04}, {25002, 1,  7,  0,0x04}, {25015,15,  4,  0,0x04}
};
const FieldTrait_Hash_Array OrderCancelRequest::_ftha(OrderCancelRequest::_traits, OrderCancelRequest::_fieldcnt);
const MsgType OrderCancelRequest::_msgtype("F");
//-------------------------------------------------------------------------------------------------
const FieldTrait ListStatus::_traits[]
{
   {  55,15,  1,  0,0x05}, {  60,22,  9,  0,0x04}, {  66, 1,  2,  0,0x04}, {  73, 1, 10,  0,0x0c},
   { 429, 1,  6,  0,0x05}, { 431, 1,  7,  0,0x05}, {1385, 1,  5,  0,0x04}, {1386, 1,  8,  0,0x04},
   {25014,15,  3,  0,0x04}, {25015,15,  4,  0,0x04}
};
const FieldTrait_Hash_Array ListStatus::_ftha(ListStatus::_traits, ListStatus::_fieldcnt);
const MsgType ListStatus::_msgtype("N");
//-------------------------------------------------------------------------------------------------
const FieldTrait ListStatus::NoOrders::_traits[]
{
   {  11,15,  1,  0,0x05}, {  37, 1,  3,  0,0x04}, {  55,15,  2,  0,0x05}, {  58,15,  7,  0,0x04},
   { 103, 1,  5,  0,0x04}, {25010, 1,  4,  1,0x1c}, {25016, 1,  6,  0,0x04}
};
const FieldTrait_Hash_Array 
   ListStatus::NoOrders::_ftha(ListStatus::NoOrders::_traits, NoOrders::_fieldcnt);
const MsgType ListStatus::NoOrders::_msgtype("NoOrders");
//-------------------------------------------------------------------------------------------------
const FieldTrait *ListStatus::NoOrders::NoListTriggeringInstructions::_traits(NoListTriggeringInstructionsV1_traits);
const FieldTrait_Hash_Array& ListStatus::NoOrders::NoListTriggeringInstructions::_ftha(NoListTriggeringInstructionsV1_ftha);
const MsgType& ListStatus::NoOrders::NoListTriggeringInstructions::_msgtype(NoListTriggeringInstructionsV1_msgtype);
//-------------------------------------------------------------------------------------------------
const FieldTrait OrderAmendKeepPriorityRequest::_traits[]
{
   {  11,15,  1,  0,0x05}, {  37, 1,  3,  0,0x04}, {  38,10,  5,  0,0x05}, {  41,15,  2,  0,0x04},
   {  55,15,  4,  0,0x05}
};
const FieldTrait_Hash_Array OrderAmendKeepPriorityRequest::_ftha(OrderAmendKeepPriorityRequest::_traits, OrderAmendKeepPriorityRequest::_fieldcnt);
const MsgType OrderAmendKeepPriorityRequest::_msgtype("XAK");
//-------------------------------------------------------------------------------------------------
const FieldTrait OrderAmendReject::_traits[]
{
   {  11,15,  1,  0,0x05}, {  37, 1,  3,  0,0x04}, {  38,10,  5,  0,0x05}, {  41,15,  2,  0,0x04},
   {  55,15,  4,  0,0x05}, {  58,15,  7,  0,0x05}, {25016, 1,  6,  0,0x05}
};
const FieldTrait_Hash_Array OrderAmendReject::_ftha(OrderAmendReject::_traits, OrderAmendReject::_fieldcnt);
const MsgType OrderAmendReject::_msgtype("XAR");
//-------------------------------------------------------------------------------------------------
const FieldTrait OrderCancelRequestAndNewOrderSingle::_traits[]
{
   {  11,15,  7,  2,0x15}, {  18, 7, 10,  2,0x14}, {  37, 1,  3,  0,0x04}, {  38,10,  8,  2,0x14},
   {  40, 7,  9,  2,0x15}, {  41,15,  5,  0,0x04}, {  44,11, 11,  2,0x14}, {  54, 7, 18,  2,0x15},
   {  55,15, 19,  2,0x15}, {  59, 7, 20,  2,0x14}, { 111,10, 21,  2,0x14}, { 152,10, 22,  2,0x14},
   { 847, 1, 23,  2,0x14}, {1100, 7, 12,  3,0x14}, {1101, 7, 13,  3,0x14}, {1102,11, 14,  3,0x14},
   {1107, 7, 15,  3,0x14}, {1109, 7, 16,  3,0x14}, {7940, 1, 24,  2,0x14}, {25001, 7, 25,  2,0x14},
   {25002, 1,  6,  0,0x04}, {25009, 1, 17,  3,0x14}, {25033, 1,  1,  0,0x05}, {25034,15,  4,  0,0x04},
   {25038, 1,  2,  0,0x04}
};
const FieldTrait_Hash_Array OrderCancelRequestAndNewOrderSingle::_ftha(OrderCancelRequestAndNewOrderSingle::_traits, OrderCancelRequestAndNewOrderSingle::_fieldcnt);
const MsgType OrderCancelRequestAndNewOrderSingle::_msgtype("XCN");
//-------------------------------------------------------------------------------------------------
const FieldTrait LimitQuery::_traits[]
{
   {6136,15,  1,  0,0x05}
};
const FieldTrait_Hash_Array LimitQuery::_ftha(LimitQuery::_traits, LimitQuery::_fieldcnt);
const MsgType LimitQuery::_msgtype("XLQ");
//-------------------------------------------------------------------------------------------------
const FieldTrait LimitResponse::_traits[]
{
   {6136,15,  1,  0,0x05}, {25003, 1,  2,  0,0x0d}
};
const FieldTrait_Hash_Array LimitResponse::_ftha(LimitResponse::_traits, LimitResponse::_fieldcnt);
const MsgType LimitResponse::_msgtype("XLR");
//-------------------------------------------------------------------------------------------------
const FieldTrait LimitResponse::NoLimitIndicators::_traits[]
{
   {25004, 7,  1,  0,0x05}, {25005, 1,  2,  0,0x05}, {25006, 1,  3,  0,0x05}, {25007, 1,  4,  0,0x04},
   {25008, 7,  5,  0,0x04}
};
const FieldTrait_Hash_Array 
   LimitResponse::NoLimitIndicators::_ftha(LimitResponse::NoLimitIndicators::_traits, NoLimitIndicators::_fieldcnt);
const MsgType LimitResponse::NoLimitIndicators::_msgtype("NoLimitIndicators");
//-------------------------------------------------------------------------------------------------
const FieldTrait header::_traits[]
{
   {   8,15,  1,  0,0x64}, {   9, 2,  2,  0,0x64}, {  34, 4,  6,  0,0x05}, {  35,15,  3,  0,0x44},
   {  49,15,  4,  0,0x05}, {  52,22,  7,  0,0x05}, {  56,15,  5,  0,0x05}, {25000, 1,  8,  0,0x04}
};
const FieldTrait_Hash_Array header::_ftha(header::_traits, header::_fieldcnt);
const MsgType header::_msgtype("header");
//-------------------------------------------------------------------------------------------------
const FieldTrait OrderMassCancelRequest::_traits[]
{
   {  11,15,  2,  0,0x05}, {  55,15,  1,  0,0x05}, { 530, 7,  3,  0,0x05}
};
const FieldTrait_Hash_Array OrderMassCancelRequest::_ftha(OrderMassCancelRequest::_traits, OrderMassCancelRequest::_fieldcnt);
const MsgType OrderMassCancelRequest::_msgtype("q");
//-------------------------------------------------------------------------------------------------
const FieldTrait OrderMassCancelReport::_traits[]
{
   {  11,15,  2,  0,0x05}, {  55,15,  1,  0,0x05}, {  58,15,  8,  0,0x04}, { 530, 7,  3,  0,0x05},
   { 531, 7,  4,  0,0x05}, { 532, 1,  5,  0,0x04}, { 533, 1,  6,  0,0x04}, {25016, 1,  7,  0,0x04}
};
const FieldTrait_Hash_Array OrderMassCancelReport::_ftha(OrderMassCancelReport::_traits, OrderMassCancelReport::_fieldcnt);
const MsgType OrderMassCancelReport::_msgtype("r");
//-------------------------------------------------------------------------------------------------
const FieldTrait trailer::_traits[]
{
   {  10,15,  1,  0,0x64}
};
const FieldTrait_Hash_Array trailer::_ftha(trailer::_traits, trailer::_fieldcnt);
const MsgType trailer::_msgtype("trailer");

} // namespace NewOroFix44OE
} // namespace FIX8
