//-------------------------------------------------------------------------------------------------
// *** f8c generated file: DO NOT EDIT! Created: 2025-07-26 15:49:19 ***
//-------------------------------------------------------------------------------------------------
/*

Fix8 is released under the GNU LESSER GENERAL PUBLIC LICENSE Version 3.

Fix8 Open Source FIX Engine.
Copyright (C) 2010-25 David L. Dight <fix@fix8.org>

Fix8 is free software: you can  redistribute it and / or modify  it under the  terms of the
GNU Lesser General  Public License as  published  by the Free  Software Foundation,  either
version 3 of the License, or (at your option) any later version.

Fix8 is distributed in the hope  that it will be useful, but WITHOUT ANY WARRANTY;  without
even the  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

You should  have received a copy of the GNU Lesser General Public  License along with Fix8.
If not, see <http://www.gnu.org/licenses/>.

*******************************************************************************************
*                Special note for Fix8 compiler generated source code                     *
*                                                                                         *
* Binary works  that are the results of compilation of code that is generated by the Fix8 *
* compiler  can be released  without releasing your  source code as  long as your  binary *
* links dynamically  against an  unmodified version of the Fix8 library.  You are however *
* required to leave the copyright text in the generated code.                             *
*                                                                                         *
*******************************************************************************************

BECAUSE THE PROGRAM IS  LICENSED FREE OF  CHARGE, THERE IS NO  WARRANTY FOR THE PROGRAM, TO
THE EXTENT  PERMITTED  BY  APPLICABLE  LAW.  EXCEPT WHEN  OTHERWISE  STATED IN  WRITING THE
COPYRIGHT HOLDERS AND/OR OTHER PARTIES  PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY OF ANY
KIND,  EITHER EXPRESSED   OR   IMPLIED,  INCLUDING,  BUT   NOT  LIMITED   TO,  THE  IMPLIED
WARRANTIES  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS TO
THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE,
YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

IN NO EVENT UNLESS REQUIRED  BY APPLICABLE LAW  OR AGREED TO IN  WRITING WILL ANY COPYRIGHT
HOLDER, OR  ANY OTHER PARTY  WHO MAY MODIFY  AND/OR REDISTRIBUTE  THE PROGRAM AS  PERMITTED
ABOVE,  BE  LIABLE  TO  YOU  FOR  DAMAGES,  INCLUDING  ANY  GENERAL, SPECIAL, INCIDENTAL OR
CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT
NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR
THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH
HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

*/

//-------------------------------------------------------------------------------------------------
#include <fix8/f8config.h>
#if defined FIX8_MAGIC_NUM && FIX8_MAGIC_NUM > 16793603L
#error NewOroFix44OE_types.cpp version 1.4.3 is out of date. Please regenerate with f8c.
#endif
//-------------------------------------------------------------------------------------------------
// NewOroFix44OE_types.cpp
//-------------------------------------------------------------------------------------------------
#include <iostream>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <vector>
#include <map>
#include <list>
#include <set>
#include <iterator>
#include <algorithm>
#include <cerrno>
#include <string.h>
// f8 includes
#include <fix8/f8exception.hpp>
#include <fix8/hypersleep.hpp>
#include <fix8/mpmc.hpp>
#include <fix8/thread.hpp>
#include <fix8/f8types.hpp>
#include <fix8/f8utils.hpp>
#include <fix8/tickval.hpp>
#include <fix8/logger.hpp>
#include <fix8/traits.hpp>
#include <fix8/field.hpp>
#include <fix8/message.hpp>
#include "NewOroFix44OE_types.hpp"
//-------------------------------------------------------------------------------------------------
namespace FIX8 {
namespace NewOroFix44OE {

namespace {

//-------------------------------------------------------------------------------------------------
const f8String BeginString_realm[]  
   { "FIX.4.4" };
const char *BeginString_descriptions[]  
   { "FIX44" };
const char ExecInst_realm[]  
   { '6' };
const char *ExecInst_descriptions[]  
   { "PARTICIPATE_DONT_INITIATE" };
const f8String MsgType_realm[]  
   { "0", "1", "3", "5", "8", "9", "A", "B", "D", "E", "F", "N", "XAK", "XAR", "XCN", "XLQ", "XLR", "q", "r" };
const char *MsgType_descriptions[]  
   { "HEARTBEAT", "TEST_REQUEST", "REJECT", "LOGOUT", "EXECUTION_REPORT", "ORDER_CANCEL_REJECT", "LOGON", "NEWS", "NEW_ORDER_SINGLE", "NEW_ORDER_LIST", "ORDER_CANCEL_REQUEST", "LIST_STATUS", "ORDER_AMEND_KEEP_PRIORITY_REQUEST", "ORDER_AMEND_REJECT", "ORDER_CANCEL_REQUEST_AND_NEW_ORDER_SINGLE", "LIMIT_QUERY", "LIMIT_RESPONSE", "ORDER_MASS_CANCEL_REQUEST", "ORDER_MASS_CANCEL_REPORT" };
const char OrdStatus_realm[]  
   { '0', '1', '2', '4', '6', '8', 'A', 'C' };
const char *OrdStatus_descriptions[]  
   { "NEW", "PARTIALLY_FILLED", "FILLED", "CANCELED", "PENDING_CANCEL", "REJECTED", "PENDING_NEW", "EXPIRED" };
const char OrdType_realm[]  
   { '1', '2', '3', '4' };
const char *OrdType_descriptions[]  
   { "MARKET", "LIMIT", "STOP", "STOP_LIMIT" };
const char Side_realm[]  
   { '1', '2' };
const char *Side_descriptions[]  
   { "BUY", "SELL" };
const char TimeInForce_realm[]  
   { '1', '3', '4' };
const char *TimeInForce_descriptions[]  
   { "GOOD_TILL_CANCEL", "IMMEDIATE_OR_CANCEL", "FILL_OR_KILL" };
const int EncryptMethod_realm[]  
   { 0 };
const char *EncryptMethod_descriptions[]  
   { "NONE" };
const int OrdRejReason_realm[]  
   { 99 };
const char *OrdRejReason_descriptions[]  
   { "OTHER" };
const int MiscFeeType_realm[]  
   { 4 };
const char *MiscFeeType_descriptions[]  
   { "EXCHANGE_FEES" };
const char ResetSeqNumFlag_realm[]  
   { 'N', 'Y' };
const char *ResetSeqNumFlag_descriptions[]  
   { "NO", "YES" };
const char ExecType_realm[]  
   { '0', '4', '5', '8', 'C', 'F' };
const char *ExecType_descriptions[]  
   { "NEW", "CANCELED", "REPLACED", "REJECTED", "EXPIRED", "TRADE" };
const int SessionRejectReason_realm[]  
   { 0, 1, 2, 3, 5, 6, 8, 10, 13, 14, 15, 16, 99 };
const char *SessionRejectReason_descriptions[]  
   { "INVALID_TAG_NUMBER", "REQUIRED_TAG_MISSING", "TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE", "UNDEFINED_TAG", "VALUE_IS_INCORRECT", "INCORRECT_DATA_FORMAT_FOR_VALUE", "SIGNATURE_PROBLEM", "SENDINGTIME_ACCURACY_PROBLEM", "TAG_APPEARS_MORE_THAN_ONCE", "TAG_SPECIFIED_OUT_OF_REQUIRED_ORDER", "REPEATING_GROUP_FIELDS_OUT_OF_ORDER", "INCORRECT_NUMINGROUP_COUNT_FOR_REPEATING_GROUP", "OTHER" };
const int ListStatusType_realm[]  
   { 2, 4, 5, 100 };
const char *ListStatusType_descriptions[]  
   { "RESPONSE", "EXEC_STARTED", "ALL_DONE", "UPDATED" };
const int ListOrderStatus_realm[]  
   { 3, 6, 7 };
const char *ListOrderStatus_descriptions[]  
   { "EXECUTING", "ALL_DONE", "REJECT" };
const char CxlRejResponseTo_realm[]  
   { '1' };
const char *CxlRejResponseTo_descriptions[]  
   { "ORDER_CANCEL_REQUEST" };
const char MassCancelRequestType_realm[]  
   { '1' };
const char *MassCancelRequestType_descriptions[]  
   { "CANCEL_SYMBOL_ORDERS" };
const char MassCancelResponse_realm[]  
   { '0', '1' };
const char *MassCancelResponse_descriptions[]  
   { "CANCEL_REQUEST_REJECTED", "CANCEL_SYMBOL_ORDERS" };
const int MassCancelRejectReason_realm[]  
   { 99 };
const char *MassCancelRejectReason_descriptions[]  
   { "OTHER" };
const f8String MatchType_realm[]  
   { "1", "4" };
const char *MatchType_descriptions[]  
   { "ONE_PARTY_TRADE_REPORT", "AUTO_MATCH" };
const char AggressorIndicator_realm[]  
   { 'N', 'Y' };
const char *AggressorIndicator_descriptions[]  
   { "ORDER_INITIATOR_IS_PASSIVE", "ORDER_INITIATOR_IS_AGGRESSOR" };
const char TriggerType_realm[]  
   { '4' };
const char *TriggerType_descriptions[]  
   { "PRICE_MOVEMENT" };
const char TriggerAction_realm[]  
   { '1' };
const char *TriggerAction_descriptions[]  
   { "ACTIVATE" };
const char TriggerPriceType_realm[]  
   { '2' };
const char *TriggerPriceType_descriptions[]  
   { "LAST_TRADE" };
const char TriggerPriceDirection_realm[]  
   { 'D', 'U' };
const char *TriggerPriceDirection_descriptions[]  
   { "TRIGGER_IF_THE_PRICE_OF_THE_SPECIFIED_TYPE_GOES_DOWN_TO_OR_THROUGH_THE_SPECIFIED_TRIGGER_PRICE", "TRIGGER_IF_THE_PRICE_OF_THE_SPECIFIED_TYPE_GOES_UP_TO_OR_THROUGH_THE_SPECIFIED_TRIGGER_PRICE" };
const int ContingencyType_realm[]  
   { 1, 2 };
const char *ContingencyType_descriptions[]  
   { "ONE_CANCELS_THE_OTHER", "ONE_TRIGGERS_THE_OTHER" };
const int ListRejectReason_realm[]  
   { 99 };
const char *ListRejectReason_descriptions[]  
   { "OTHER" };
const char SelfTradePreventionMode_realm[]  
   { '1', '2', '3', '4', '5' };
const char *SelfTradePreventionMode_descriptions[]  
   { "NONE", "EXPIRE_TAKER", "EXPIRE_MAKER", "EXPIRE_BOTH", "DECREMENT" };
const int CancelRestrictions_realm[]  
   { 1, 2 };
const char *CancelRestrictions_descriptions[]  
   { "ONLY_NEW", "ONLY_PARTIALLY_FILLED" };
const char LimitType_realm[]  
   { '1', '2' };
const char *LimitType_descriptions[]  
   { "ORDER_LIMIT", "MESSAGE_LIMIT" };
const char LimitResetIntervalResolution_realm[]  
   { 'd', 'h', 'm', 's' };
const char *LimitResetIntervalResolution_descriptions[]  
   { "DAY", "HOUR", "MINUTE", "SECOND" };
const char ListTriggerType_realm[]  
   { '1', '2', '3' };
const char *ListTriggerType_descriptions[]  
   { "ACTIVATED", "PARTIALLY_FILLED", "FILLED" };
const char ListTriggerAction_realm[]  
   { '1', '2' };
const char *ListTriggerAction_descriptions[]  
   { "RELEASE", "CANCEL" };
const int WorkingFloor_realm[]  
   { 1, 2, 3 };
const char *WorkingFloor_descriptions[]  
   { "EXCHANGE", "BROKER", "SOR" };
const int OrderCancelRequestAndNewOrderSingleMode_realm[]  
   { 1, 2 };
const char *OrderCancelRequestAndNewOrderSingleMode_descriptions[]  
   { "STOP_ON_FAILURE", "ALLOW_FAILURE" };
const int MessageHandling_realm[]  
   { 1, 2 };
const char *MessageHandling_descriptions[]  
   { "UNORDERED", "SEQUENTIAL" };
const int ResponseMode_realm[]  
   { 1, 2 };
const char *ResponseMode_descriptions[]  
   { "EVERYTHING", "ONLY_ACKS" };
const int OrderRateLimitExceededMode_realm[]  
   { 1, 2 };
const char *OrderRateLimitExceededMode_descriptions[]  
   { "DO_NOTHING", "CANCEL_ONLY" };

//-------------------------------------------------------------------------------------------------
const RealmBase realmbases[] 
{
   { reinterpret_cast<const void *>(BeginString_realm), RealmBase::dt_set, FieldTrait::ft_string, 1, BeginString_descriptions },
   { reinterpret_cast<const void *>(ExecInst_realm), RealmBase::dt_set, FieldTrait::ft_char, 1, ExecInst_descriptions },
   { reinterpret_cast<const void *>(MsgType_realm), RealmBase::dt_set, FieldTrait::ft_string, 19, MsgType_descriptions },
   { reinterpret_cast<const void *>(OrdStatus_realm), RealmBase::dt_set, FieldTrait::ft_char, 8, OrdStatus_descriptions },
   { reinterpret_cast<const void *>(OrdType_realm), RealmBase::dt_set, FieldTrait::ft_char, 4, OrdType_descriptions },
   { reinterpret_cast<const void *>(Side_realm), RealmBase::dt_set, FieldTrait::ft_char, 2, Side_descriptions },
   { reinterpret_cast<const void *>(TimeInForce_realm), RealmBase::dt_set, FieldTrait::ft_char, 3, TimeInForce_descriptions },
   { reinterpret_cast<const void *>(EncryptMethod_realm), RealmBase::dt_set, FieldTrait::ft_int, 1, EncryptMethod_descriptions },
   { reinterpret_cast<const void *>(OrdRejReason_realm), RealmBase::dt_set, FieldTrait::ft_int, 1, OrdRejReason_descriptions },
   { reinterpret_cast<const void *>(MiscFeeType_realm), RealmBase::dt_set, FieldTrait::ft_int, 1, MiscFeeType_descriptions },
   { reinterpret_cast<const void *>(ResetSeqNumFlag_realm), RealmBase::dt_set, FieldTrait::ft_Boolean, 2, ResetSeqNumFlag_descriptions },
   { reinterpret_cast<const void *>(ExecType_realm), RealmBase::dt_set, FieldTrait::ft_char, 6, ExecType_descriptions },
   { reinterpret_cast<const void *>(SessionRejectReason_realm), RealmBase::dt_set, FieldTrait::ft_int, 13, SessionRejectReason_descriptions },
   { reinterpret_cast<const void *>(ListStatusType_realm), RealmBase::dt_set, FieldTrait::ft_int, 4, ListStatusType_descriptions },
   { reinterpret_cast<const void *>(ListOrderStatus_realm), RealmBase::dt_set, FieldTrait::ft_int, 3, ListOrderStatus_descriptions },
   { reinterpret_cast<const void *>(CxlRejResponseTo_realm), RealmBase::dt_set, FieldTrait::ft_char, 1, CxlRejResponseTo_descriptions },
   { reinterpret_cast<const void *>(MassCancelRequestType_realm), RealmBase::dt_set, FieldTrait::ft_char, 1, MassCancelRequestType_descriptions },
   { reinterpret_cast<const void *>(MassCancelResponse_realm), RealmBase::dt_set, FieldTrait::ft_char, 2, MassCancelResponse_descriptions },
   { reinterpret_cast<const void *>(MassCancelRejectReason_realm), RealmBase::dt_set, FieldTrait::ft_int, 1, MassCancelRejectReason_descriptions },
   { reinterpret_cast<const void *>(MatchType_realm), RealmBase::dt_set, FieldTrait::ft_string, 2, MatchType_descriptions },
   { reinterpret_cast<const void *>(AggressorIndicator_realm), RealmBase::dt_set, FieldTrait::ft_Boolean, 2, AggressorIndicator_descriptions },
   { reinterpret_cast<const void *>(TriggerType_realm), RealmBase::dt_set, FieldTrait::ft_char, 1, TriggerType_descriptions },
   { reinterpret_cast<const void *>(TriggerAction_realm), RealmBase::dt_set, FieldTrait::ft_char, 1, TriggerAction_descriptions },
   { reinterpret_cast<const void *>(TriggerPriceType_realm), RealmBase::dt_set, FieldTrait::ft_char, 1, TriggerPriceType_descriptions },
   { reinterpret_cast<const void *>(TriggerPriceDirection_realm), RealmBase::dt_set, FieldTrait::ft_char, 2, TriggerPriceDirection_descriptions },
   { reinterpret_cast<const void *>(ContingencyType_realm), RealmBase::dt_set, FieldTrait::ft_int, 2, ContingencyType_descriptions },
   { reinterpret_cast<const void *>(ListRejectReason_realm), RealmBase::dt_set, FieldTrait::ft_int, 1, ListRejectReason_descriptions },
   { reinterpret_cast<const void *>(SelfTradePreventionMode_realm), RealmBase::dt_set, FieldTrait::ft_char, 5, SelfTradePreventionMode_descriptions },
   { reinterpret_cast<const void *>(CancelRestrictions_realm), RealmBase::dt_set, FieldTrait::ft_int, 2, CancelRestrictions_descriptions },
   { reinterpret_cast<const void *>(LimitType_realm), RealmBase::dt_set, FieldTrait::ft_char, 2, LimitType_descriptions },
   { reinterpret_cast<const void *>(LimitResetIntervalResolution_realm), RealmBase::dt_set, FieldTrait::ft_char, 4, LimitResetIntervalResolution_descriptions },
   { reinterpret_cast<const void *>(ListTriggerType_realm), RealmBase::dt_set, FieldTrait::ft_char, 3, ListTriggerType_descriptions },
   { reinterpret_cast<const void *>(ListTriggerAction_realm), RealmBase::dt_set, FieldTrait::ft_char, 2, ListTriggerAction_descriptions },
   { reinterpret_cast<const void *>(WorkingFloor_realm), RealmBase::dt_set, FieldTrait::ft_int, 3, WorkingFloor_descriptions },
   { reinterpret_cast<const void *>(OrderCancelRequestAndNewOrderSingleMode_realm), RealmBase::dt_set, FieldTrait::ft_int, 2, OrderCancelRequestAndNewOrderSingleMode_descriptions },
   { reinterpret_cast<const void *>(MessageHandling_realm), RealmBase::dt_set, FieldTrait::ft_int, 2, MessageHandling_descriptions },
   { reinterpret_cast<const void *>(ResponseMode_realm), RealmBase::dt_set, FieldTrait::ft_int, 2, ResponseMode_descriptions },
   { reinterpret_cast<const void *>(OrderRateLimitExceededMode_realm), RealmBase::dt_set, FieldTrait::ft_int, 2, OrderRateLimitExceededMode_descriptions },
};

//-------------------------------------------------------------------------------------------------

} // namespace

//-------------------------------------------------------------------------------------------------
extern const NewOroFix44OE_BaseEntry::Pair fldpairs[];
const NewOroFix44OE_BaseEntry::Pair fldpairs[] 
{
   { 8, { Type2Type<NewOroFix44OE::BeginString, f8String>(), "BeginString", 8, &NewOroFix44OE::realmbases[0] } },
   { 9, { Type2Type<NewOroFix44OE::BodyLength>(), "BodyLength", 9 } },
   { 10, { Type2Type<NewOroFix44OE::CheckSum>(), "CheckSum", 10 } },
   { 11, { Type2Type<NewOroFix44OE::ClOrdID>(), "ClOrdID", 11 } },
   { 14, { Type2Type<NewOroFix44OE::CumQty>(), "CumQty", 14 } },
   { 17, { Type2Type<NewOroFix44OE::ExecID>(), "ExecID", 17 } },
   { 18, { Type2Type<NewOroFix44OE::ExecInst, char>(), "ExecInst", 18, &NewOroFix44OE::realmbases[1] } },
   { 31, { Type2Type<NewOroFix44OE::LastPx>(), "LastPx", 31 } },
   { 32, { Type2Type<NewOroFix44OE::LastQty>(), "LastQty", 32 } },
   { 34, { Type2Type<NewOroFix44OE::MsgSeqNum>(), "MsgSeqNum", 34 } },
   { 35, { Type2Type<NewOroFix44OE::MsgType, f8String>(), "MsgType", 35, &NewOroFix44OE::realmbases[2] } },
   { 37, { Type2Type<NewOroFix44OE::OrderID>(), "OrderID", 37 } },
   { 38, { Type2Type<NewOroFix44OE::OrderQty>(), "OrderQty", 38 } },
   { 39, { Type2Type<NewOroFix44OE::OrdStatus, char>(), "OrdStatus", 39, &NewOroFix44OE::realmbases[3] } },
   { 40, { Type2Type<NewOroFix44OE::OrdType, char>(), "OrdType", 40, &NewOroFix44OE::realmbases[4] } },
   { 41, { Type2Type<NewOroFix44OE::OrigClOrdID>(), "OrigClOrdID", 41 } },
   { 44, { Type2Type<NewOroFix44OE::Price>(), "Price", 44 } },
   { 45, { Type2Type<NewOroFix44OE::RefSeqNum>(), "RefSeqNum", 45 } },
   { 49, { Type2Type<NewOroFix44OE::SenderCompID>(), "SenderCompID", 49 } },
   { 52, { Type2Type<NewOroFix44OE::SendingTime>(), "SendingTime", 52 } },
   { 54, { Type2Type<NewOroFix44OE::Side, char>(), "Side", 54, &NewOroFix44OE::realmbases[5] } },
   { 55, { Type2Type<NewOroFix44OE::Symbol>(), "Symbol", 55 } },
   { 56, { Type2Type<NewOroFix44OE::TargetCompID>(), "TargetCompID", 56 } },
   { 58, { Type2Type<NewOroFix44OE::Text>(), "Text", 58 } },
   { 59, { Type2Type<NewOroFix44OE::TimeInForce, char>(), "TimeInForce", 59, &NewOroFix44OE::realmbases[6] } },
   { 60, { Type2Type<NewOroFix44OE::TransactTime>(), "TransactTime", 60 } },
   { 66, { Type2Type<NewOroFix44OE::ListID>(), "ListID", 66 } },
   { 70, { Type2Type<NewOroFix44OE::AllocID>(), "AllocID", 70 } },
   { 73, { Type2Type<NewOroFix44OE::NoOrders>(), "NoOrders", 73 } },
   { 95, { Type2Type<NewOroFix44OE::RawDataLength>(), "RawDataLength", 95 } },
   { 96, { Type2Type<NewOroFix44OE::RawData>(), "RawData", 96 } },
   { 98, { Type2Type<NewOroFix44OE::EncryptMethod, int>(), "EncryptMethod", 98, &NewOroFix44OE::realmbases[7] } },
   { 103, { Type2Type<NewOroFix44OE::OrdRejReason, int>(), "OrdRejReason", 103, &NewOroFix44OE::realmbases[8] } },
   { 108, { Type2Type<NewOroFix44OE::HeartBtInt>(), "HeartBtInt", 108 } },
   { 111, { Type2Type<NewOroFix44OE::MaxFloor>(), "MaxFloor", 111 } },
   { 112, { Type2Type<NewOroFix44OE::TestReqID>(), "TestReqID", 112 } },
   { 136, { Type2Type<NewOroFix44OE::NoMiscFees>(), "NoMiscFees", 136 } },
   { 137, { Type2Type<NewOroFix44OE::MiscFeeAmt>(), "MiscFeeAmt", 137 } },
   { 138, { Type2Type<NewOroFix44OE::MiscFeeCurr>(), "MiscFeeCurr", 138 } },
   { 139, { Type2Type<NewOroFix44OE::MiscFeeType, int>(), "MiscFeeType", 139, &NewOroFix44OE::realmbases[9] } },
   { 141, { Type2Type<NewOroFix44OE::ResetSeqNumFlag, char>(), "ResetSeqNumFlag", 141, &NewOroFix44OE::realmbases[10] } },
   { 148, { Type2Type<NewOroFix44OE::Headline>(), "Headline", 148 } },
   { 150, { Type2Type<NewOroFix44OE::ExecType, char>(), "ExecType", 150, &NewOroFix44OE::realmbases[11] } },
   { 151, { Type2Type<NewOroFix44OE::LeavesQty>(), "LeavesQty", 151 } },
   { 152, { Type2Type<NewOroFix44OE::CashOrderQty>(), "CashOrderQty", 152 } },
   { 371, { Type2Type<NewOroFix44OE::RefTagID>(), "RefTagID", 371 } },
   { 372, { Type2Type<NewOroFix44OE::RefMsgType>(), "RefMsgType", 372 } },
   { 373, { Type2Type<NewOroFix44OE::SessionRejectReason, int>(), "SessionRejectReason", 373, &NewOroFix44OE::realmbases[12] } },
   { 429, { Type2Type<NewOroFix44OE::ListStatusType, int>(), "ListStatusType", 429, &NewOroFix44OE::realmbases[13] } },
   { 431, { Type2Type<NewOroFix44OE::ListOrderStatus, int>(), "ListOrderStatus", 431, &NewOroFix44OE::realmbases[14] } },
   { 434, { Type2Type<NewOroFix44OE::CxlRejResponseTo, char>(), "CxlRejResponseTo", 434, &NewOroFix44OE::realmbases[15] } },
   { 530, { Type2Type<NewOroFix44OE::MassCancelRequestType, char>(), "MassCancelRequestType", 530, &NewOroFix44OE::realmbases[16] } },
   { 531, { Type2Type<NewOroFix44OE::MassCancelResponse, char>(), "MassCancelResponse", 531, &NewOroFix44OE::realmbases[17] } },
   { 532, { Type2Type<NewOroFix44OE::MassCancelRejectReason, int>(), "MassCancelRejectReason", 532, &NewOroFix44OE::realmbases[18] } },
   { 533, { Type2Type<NewOroFix44OE::TotalAffectedOrders>(), "TotalAffectedOrders", 533 } },
   { 553, { Type2Type<NewOroFix44OE::Username>(), "Username", 553 } },
   { 574, { Type2Type<NewOroFix44OE::MatchType, f8String>(), "MatchType", 574, &NewOroFix44OE::realmbases[19] } },
   { 636, { Type2Type<NewOroFix44OE::WorkingIndicator>(), "WorkingIndicator", 636 } },
   { 847, { Type2Type<NewOroFix44OE::TargetStrategy>(), "TargetStrategy", 847 } },
   { 1003, { Type2Type<NewOroFix44OE::TradeID>(), "TradeID", 1003 } },
   { 1057, { Type2Type<NewOroFix44OE::AggressorIndicator, char>(), "AggressorIndicator", 1057, &NewOroFix44OE::realmbases[20] } },
   { 1100, { Type2Type<NewOroFix44OE::TriggerType, char>(), "TriggerType", 1100, &NewOroFix44OE::realmbases[21] } },
   { 1101, { Type2Type<NewOroFix44OE::TriggerAction, char>(), "TriggerAction", 1101, &NewOroFix44OE::realmbases[22] } },
   { 1102, { Type2Type<NewOroFix44OE::TriggerPrice>(), "TriggerPrice", 1102 } },
   { 1107, { Type2Type<NewOroFix44OE::TriggerPriceType, char>(), "TriggerPriceType", 1107, &NewOroFix44OE::realmbases[23] } },
   { 1109, { Type2Type<NewOroFix44OE::TriggerPriceDirection, char>(), "TriggerPriceDirection", 1109, &NewOroFix44OE::realmbases[24] } },
   { 1385, { Type2Type<NewOroFix44OE::ContingencyType, int>(), "ContingencyType", 1385, &NewOroFix44OE::realmbases[25] } },
   { 1386, { Type2Type<NewOroFix44OE::ListRejectReason, int>(), "ListRejectReason", 1386, &NewOroFix44OE::realmbases[26] } },
   { 6136, { Type2Type<NewOroFix44OE::ReqID>(), "ReqID", 6136 } },
   { 7940, { Type2Type<NewOroFix44OE::StrategyID>(), "StrategyID", 7940 } },
   { 9406, { Type2Type<NewOroFix44OE::DropCopyFlag>(), "DropCopyFlag", 9406 } },
   { 25000, { Type2Type<NewOroFix44OE::RecvWindow>(), "RecvWindow", 25000 } },
   { 25001, { Type2Type<NewOroFix44OE::SelfTradePreventionMode, char>(), "SelfTradePreventionMode", 25001, &NewOroFix44OE::realmbases[27] } },
   { 25002, { Type2Type<NewOroFix44OE::CancelRestrictions, int>(), "CancelRestrictions", 25002, &NewOroFix44OE::realmbases[28] } },
   { 25003, { Type2Type<NewOroFix44OE::NoLimitIndicators>(), "NoLimitIndicators", 25003 } },
   { 25004, { Type2Type<NewOroFix44OE::LimitType, char>(), "LimitType", 25004, &NewOroFix44OE::realmbases[29] } },
   { 25005, { Type2Type<NewOroFix44OE::LimitCount>(), "LimitCount", 25005 } },
   { 25006, { Type2Type<NewOroFix44OE::LimitMax>(), "LimitMax", 25006 } },
   { 25007, { Type2Type<NewOroFix44OE::LimitResetInterval>(), "LimitResetInterval", 25007 } },
   { 25008, { Type2Type<NewOroFix44OE::LimitResetIntervalResolution, char>(), "LimitResetIntervalResolution", 25008, &NewOroFix44OE::realmbases[30] } },
   { 25009, { Type2Type<NewOroFix44OE::TriggerTrailingDeltaBips>(), "TriggerTrailingDeltaBips", 25009 } },
   { 25010, { Type2Type<NewOroFix44OE::NoListTriggeringInstructions>(), "NoListTriggeringInstructions", 25010 } },
   { 25011, { Type2Type<NewOroFix44OE::ListTriggerType, char>(), "ListTriggerType", 25011, &NewOroFix44OE::realmbases[31] } },
   { 25012, { Type2Type<NewOroFix44OE::ListTriggerTriggerIndex>(), "ListTriggerTriggerIndex", 25012 } },
   { 25013, { Type2Type<NewOroFix44OE::ListTriggerAction, char>(), "ListTriggerAction", 25013, &NewOroFix44OE::realmbases[32] } },
   { 25014, { Type2Type<NewOroFix44OE::ClListID>(), "ClListID", 25014 } },
   { 25015, { Type2Type<NewOroFix44OE::OrigClListID>(), "OrigClListID", 25015 } },
   { 25016, { Type2Type<NewOroFix44OE::ErrorCode>(), "ErrorCode", 25016 } },
   { 25017, { Type2Type<NewOroFix44OE::CumQuoteQty>(), "CumQuoteQty", 25017 } },
   { 25018, { Type2Type<NewOroFix44OE::OrderCreationTime>(), "OrderCreationTime", 25018 } },
   { 25021, { Type2Type<NewOroFix44OE::WorkingFloor, int>(), "WorkingFloor", 25021, &NewOroFix44OE::realmbases[33] } },
   { 25022, { Type2Type<NewOroFix44OE::TrailingTime>(), "TrailingTime", 25022 } },
   { 25023, { Type2Type<NewOroFix44OE::WorkingTime>(), "WorkingTime", 25023 } },
   { 25024, { Type2Type<NewOroFix44OE::PreventedMatchID>(), "PreventedMatchID", 25024 } },
   { 25025, { Type2Type<NewOroFix44OE::PreventedExecutionPrice>(), "PreventedExecutionPrice", 25025 } },
   { 25026, { Type2Type<NewOroFix44OE::PreventedExecutionQty>(), "PreventedExecutionQty", 25026 } },
   { 25027, { Type2Type<NewOroFix44OE::TradeGroupID>(), "TradeGroupID", 25027 } },
   { 25028, { Type2Type<NewOroFix44OE::CounterSymbol>(), "CounterSymbol", 25028 } },
   { 25029, { Type2Type<NewOroFix44OE::CounterOrderID>(), "CounterOrderID", 25029 } },
   { 25030, { Type2Type<NewOroFix44OE::PreventedQty>(), "PreventedQty", 25030 } },
   { 25031, { Type2Type<NewOroFix44OE::LastPreventedQty>(), "LastPreventedQty", 25031 } },
   { 25032, { Type2Type<NewOroFix44OE::SOR>(), "SOR", 25032 } },
   { 25033, { Type2Type<NewOroFix44OE::OrderCancelRequestAndNewOrderSingleMode, int>(), "OrderCancelRequestAndNewOrderSingleMode", 25033, &NewOroFix44OE::realmbases[34] } },
   { 25034, { Type2Type<NewOroFix44OE::CancelClOrdID>(), "CancelClOrdID", 25034 } },
   { 25035, { Type2Type<NewOroFix44OE::MessageHandling, int>(), "MessageHandling", 25035, &NewOroFix44OE::realmbases[35] } },
   { 25036, { Type2Type<NewOroFix44OE::ResponseMode, int>(), "ResponseMode", 25036, &NewOroFix44OE::realmbases[36] } },
   { 25037, { Type2Type<NewOroFix44OE::UUID>(), "UUID", 25037 } },
   { 25038, { Type2Type<NewOroFix44OE::OrderRateLimitExceededMode, int>(), "OrderRateLimitExceededMode", 25038, &NewOroFix44OE::realmbases[37] } }
}; // 108
} // namespace NewOroFix44OE

} // namespace FIX8
