//-------------------------------------------------------------------------------------------------
// *** f8c generated file: DO NOT EDIT! Created: 2025-07-26 15:49:22 ***
//-------------------------------------------------------------------------------------------------
/*

Fix8 is released under the GNU LESSER GENERAL PUBLIC LICENSE Version 3.

Fix8 Open Source FIX Engine.
Copyright (C) 2010-25 David L. Dight <fix@fix8.org>

Fix8 is free software: you can  redistribute it and / or modify  it under the  terms of the
GNU Lesser General  Public License as  published  by the Free  Software Foundation,  either
version 3 of the License, or (at your option) any later version.

Fix8 is distributed in the hope  that it will be useful, but WITHOUT ANY WARRANTY;  without
even the  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

You should  have received a copy of the GNU Lesser General Public  License along with Fix8.
If not, see <http://www.gnu.org/licenses/>.

*******************************************************************************************
*                Special note for Fix8 compiler generated source code                     *
*                                                                                         *
* Binary works  that are the results of compilation of code that is generated by the Fix8 *
* compiler  can be released  without releasing your  source code as  long as your  binary *
* links dynamically  against an  unmodified version of the Fix8 library.  You are however *
* required to leave the copyright text in the generated code.                             *
*                                                                                         *
*******************************************************************************************

BECAUSE THE PROGRAM IS  LICENSED FREE OF  CHARGE, THERE IS NO  WARRANTY FOR THE PROGRAM, TO
THE EXTENT  PERMITTED  BY  APPLICABLE  LAW.  EXCEPT WHEN  OTHERWISE  STATED IN  WRITING THE
COPYRIGHT HOLDERS AND/OR OTHER PARTIES  PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY OF ANY
KIND,  EITHER EXPRESSED   OR   IMPLIED,  INCLUDING,  BUT   NOT  LIMITED   TO,  THE  IMPLIED
WARRANTIES  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS TO
THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE,
YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

IN NO EVENT UNLESS REQUIRED  BY APPLICABLE LAW  OR AGREED TO IN  WRITING WILL ANY COPYRIGHT
HOLDER, OR  ANY OTHER PARTY  WHO MAY MODIFY  AND/OR REDISTRIBUTE  THE PROGRAM AS  PERMITTED
ABOVE,  BE  LIABLE  TO  YOU  FOR  DAMAGES,  INCLUDING  ANY  GENERAL, SPECIAL, INCIDENTAL OR
CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT
NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR
THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH
HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

*/

//-------------------------------------------------------------------------------------------------
#include <fix8/f8config.h>
#if defined FIX8_MAGIC_NUM && FIX8_MAGIC_NUM > 16793603L
#error NewOroFix44MD_types.cpp version 1.4.3 is out of date. Please regenerate with f8c.
#endif
//-------------------------------------------------------------------------------------------------
// NewOroFix44MD_types.cpp
//-------------------------------------------------------------------------------------------------
#include <iostream>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <vector>
#include <map>
#include <list>
#include <set>
#include <iterator>
#include <algorithm>
#include <cerrno>
#include <string.h>
// f8 includes
#include <fix8/f8exception.hpp>
#include <fix8/hypersleep.hpp>
#include <fix8/mpmc.hpp>
#include <fix8/thread.hpp>
#include <fix8/f8types.hpp>
#include <fix8/f8utils.hpp>
#include <fix8/tickval.hpp>
#include <fix8/logger.hpp>
#include <fix8/traits.hpp>
#include <fix8/field.hpp>
#include <fix8/message.hpp>
#include "NewOroFix44MD_types.hpp"
//-------------------------------------------------------------------------------------------------
namespace FIX8 {
namespace NewOroFix44MD {

namespace {

//-------------------------------------------------------------------------------------------------
const f8String BeginString_realm[]  
   { "FIX.4.4" };
const char *BeginString_descriptions[]  
   { "FIX44" };
const f8String MsgType_realm[]  
   { "0", "1", "3", "5", "A", "B", "V", "W", "X", "XLQ", "XLR", "Y", "x", "y" };
const char *MsgType_descriptions[]  
   { "HEARTBEAT", "TEST_REQUEST", "REJECT", "LOGOUT", "LOGON", "NEWS", "MARKET_DATA_REQUEST", "MARKET_DATA_SNAPSHOT", "MARKET_DATA_INCREMENTAL_REFRESH", "LIMIT_QUERY", "LIMIT_RESPONSE", "MARKET_DATA_REQUEST_REJECT", "INSTRUMENT_LIST_REQUEST", "INSTRUMENT_LIST" };
const int EncryptMethod_realm[]  
   { 0 };
const char *EncryptMethod_descriptions[]  
   { "NONE" };
const char ResetSeqNumFlag_realm[]  
   { 'N', 'Y' };
const char *ResetSeqNumFlag_descriptions[]  
   { "NO", "YES" };
const char SubscriptionRequestType_realm[]  
   { '1', '2' };
const char *SubscriptionRequestType_descriptions[]  
   { "Subscribe", "Unsubscribe" };
const char AggregatedBook_realm[]  
   { 'Y' };
const char *AggregatedBook_descriptions[]  
   { "BOOK_ENTRIES_TO_BE_AGGREGATED" };
const char MDEntryType_realm[]  
   { '0', '1', '2' };
const char *MDEntryType_descriptions[]  
   { "BID", "OFFER", "TRADE" };
const char MDUpdateAction_realm[]  
   { '0', '1', '2' };
const char *MDUpdateAction_descriptions[]  
   { "NEW", "CHANGE", "DELETE" };
const char MDReqRejReason_realm[]  
   { '1', '2' };
const char *MDReqRejReason_descriptions[]  
   { "DUPLICATE_MDREQID", "TOO_MANY_SUBSCRIPTIONS" };
const int SessionRejectReason_realm[]  
   { 0, 1, 2, 3, 5, 6, 8, 10, 13, 14, 15, 16, 99 };
const char *SessionRejectReason_descriptions[]  
   { "INVALID_TAG_NUMBER", "REQUIRED_TAG_MISSING", "TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE", "UNDEFINED_TAG", "VALUE_IS_INCORRECT", "INCORRECT_DATA_FORMAT_FOR_VALUE", "SIGNATURE_PROBLEM", "SENDINGTIME_ACCURACY_PROBLEM", "TAG_APPEARS_MORE_THAN_ONCE", "TAG_SPECIFIED_OUT_OF_REQUIRED_ORDER", "REPEATING_GROUP_FIELDS_OUT_OF_ORDER", "INCORRECT_NUMINGROUP_COUNT_FOR_REPEATING_GROUP", "OTHER" };
const int InstrumentListRequestType_realm[]  
   { 0, 4 };
const char *InstrumentListRequestType_descriptions[]  
   { "SINGLE_INSTRUMENT", "ALL_INSTRUMENTS" };
const char LastFragment_realm[]  
   { 'N', 'Y' };
const char *LastFragment_descriptions[]  
   { "NOT_LAST_MESSAGE", "LAST_MESSAGE" };
const char AggressorSide_realm[]  
   { '1', '2' };
const char *AggressorSide_descriptions[]  
   { "BUY", "SELL" };
const char LimitType_realm[]  
   { '2', '3' };
const char *LimitType_descriptions[]  
   { "MESSAGE_LIMIT", "SUBSCRIPTION_LIMIT" };
const char LimitResetIntervalResolution_realm[]  
   { 'd', 'h', 'm', 's' };
const char *LimitResetIntervalResolution_descriptions[]  
   { "DAY", "HOUR", "MINUTE", "SECOND" };
const int MessageHandling_realm[]  
   { 1, 2 };
const char *MessageHandling_descriptions[]  
   { "UNORDERED", "SEQUENTIAL" };

//-------------------------------------------------------------------------------------------------
const RealmBase realmbases[] 
{
   { reinterpret_cast<const void *>(BeginString_realm), RealmBase::dt_set, FieldTrait::ft_string, 1, BeginString_descriptions },
   { reinterpret_cast<const void *>(MsgType_realm), RealmBase::dt_set, FieldTrait::ft_string, 14, MsgType_descriptions },
   { reinterpret_cast<const void *>(EncryptMethod_realm), RealmBase::dt_set, FieldTrait::ft_int, 1, EncryptMethod_descriptions },
   { reinterpret_cast<const void *>(ResetSeqNumFlag_realm), RealmBase::dt_set, FieldTrait::ft_Boolean, 2, ResetSeqNumFlag_descriptions },
   { reinterpret_cast<const void *>(SubscriptionRequestType_realm), RealmBase::dt_set, FieldTrait::ft_char, 2, SubscriptionRequestType_descriptions },
   { reinterpret_cast<const void *>(AggregatedBook_realm), RealmBase::dt_set, FieldTrait::ft_Boolean, 1, AggregatedBook_descriptions },
   { reinterpret_cast<const void *>(MDEntryType_realm), RealmBase::dt_set, FieldTrait::ft_char, 3, MDEntryType_descriptions },
   { reinterpret_cast<const void *>(MDUpdateAction_realm), RealmBase::dt_set, FieldTrait::ft_char, 3, MDUpdateAction_descriptions },
   { reinterpret_cast<const void *>(MDReqRejReason_realm), RealmBase::dt_set, FieldTrait::ft_char, 2, MDReqRejReason_descriptions },
   { reinterpret_cast<const void *>(SessionRejectReason_realm), RealmBase::dt_set, FieldTrait::ft_int, 13, SessionRejectReason_descriptions },
   { reinterpret_cast<const void *>(InstrumentListRequestType_realm), RealmBase::dt_set, FieldTrait::ft_int, 2, InstrumentListRequestType_descriptions },
   { reinterpret_cast<const void *>(LastFragment_realm), RealmBase::dt_set, FieldTrait::ft_Boolean, 2, LastFragment_descriptions },
   { reinterpret_cast<const void *>(AggressorSide_realm), RealmBase::dt_set, FieldTrait::ft_char, 2, AggressorSide_descriptions },
   { reinterpret_cast<const void *>(LimitType_realm), RealmBase::dt_set, FieldTrait::ft_char, 2, LimitType_descriptions },
   { reinterpret_cast<const void *>(LimitResetIntervalResolution_realm), RealmBase::dt_set, FieldTrait::ft_char, 4, LimitResetIntervalResolution_descriptions },
   { reinterpret_cast<const void *>(MessageHandling_realm), RealmBase::dt_set, FieldTrait::ft_int, 2, MessageHandling_descriptions },
};

//-------------------------------------------------------------------------------------------------

} // namespace

//-------------------------------------------------------------------------------------------------
extern const NewOroFix44MD_BaseEntry::Pair fldpairs[];
const NewOroFix44MD_BaseEntry::Pair fldpairs[] 
{
   { 8, { Type2Type<NewOroFix44MD::BeginString, f8String>(), "BeginString", 8, &NewOroFix44MD::realmbases[0] } },
   { 9, { Type2Type<NewOroFix44MD::BodyLength>(), "BodyLength", 9 } },
   { 10, { Type2Type<NewOroFix44MD::CheckSum>(), "CheckSum", 10 } },
   { 15, { Type2Type<NewOroFix44MD::Currency>(), "Currency", 15 } },
   { 34, { Type2Type<NewOroFix44MD::MsgSeqNum>(), "MsgSeqNum", 34 } },
   { 35, { Type2Type<NewOroFix44MD::MsgType, f8String>(), "MsgType", 35, &NewOroFix44MD::realmbases[1] } },
   { 45, { Type2Type<NewOroFix44MD::RefSeqNum>(), "RefSeqNum", 45 } },
   { 49, { Type2Type<NewOroFix44MD::SenderCompID>(), "SenderCompID", 49 } },
   { 52, { Type2Type<NewOroFix44MD::SendingTime>(), "SendingTime", 52 } },
   { 55, { Type2Type<NewOroFix44MD::Symbol>(), "Symbol", 55 } },
   { 56, { Type2Type<NewOroFix44MD::TargetCompID>(), "TargetCompID", 56 } },
   { 58, { Type2Type<NewOroFix44MD::Text>(), "Text", 58 } },
   { 60, { Type2Type<NewOroFix44MD::TransactTime>(), "TransactTime", 60 } },
   { 95, { Type2Type<NewOroFix44MD::RawDataLength>(), "RawDataLength", 95 } },
   { 96, { Type2Type<NewOroFix44MD::RawData>(), "RawData", 96 } },
   { 98, { Type2Type<NewOroFix44MD::EncryptMethod, int>(), "EncryptMethod", 98, &NewOroFix44MD::realmbases[2] } },
   { 108, { Type2Type<NewOroFix44MD::HeartBtInt>(), "HeartBtInt", 108 } },
   { 112, { Type2Type<NewOroFix44MD::TestReqID>(), "TestReqID", 112 } },
   { 141, { Type2Type<NewOroFix44MD::ResetSeqNumFlag, char>(), "ResetSeqNumFlag", 141, &NewOroFix44MD::realmbases[3] } },
   { 146, { Type2Type<NewOroFix44MD::NoRelatedSym>(), "NoRelatedSym", 146 } },
   { 148, { Type2Type<NewOroFix44MD::Headline>(), "Headline", 148 } },
   { 262, { Type2Type<NewOroFix44MD::MDReqID>(), "MDReqID", 262 } },
   { 263, { Type2Type<NewOroFix44MD::SubscriptionRequestType, char>(), "SubscriptionRequestType", 263, &NewOroFix44MD::realmbases[4] } },
   { 264, { Type2Type<NewOroFix44MD::MarketDepth>(), "MarketDepth", 264 } },
   { 266, { Type2Type<NewOroFix44MD::AggregatedBook, char>(), "AggregatedBook", 266, &NewOroFix44MD::realmbases[5] } },
   { 267, { Type2Type<NewOroFix44MD::NoMDEntryTypes>(), "NoMDEntryTypes", 267 } },
   { 268, { Type2Type<NewOroFix44MD::NoMDEntries>(), "NoMDEntries", 268 } },
   { 269, { Type2Type<NewOroFix44MD::MDEntryType, char>(), "MDEntryType", 269, &NewOroFix44MD::realmbases[6] } },
   { 270, { Type2Type<NewOroFix44MD::MDEntryPx>(), "MDEntryPx", 270 } },
   { 271, { Type2Type<NewOroFix44MD::MDEntrySize>(), "MDEntrySize", 271 } },
   { 279, { Type2Type<NewOroFix44MD::MDUpdateAction, char>(), "MDUpdateAction", 279, &NewOroFix44MD::realmbases[7] } },
   { 281, { Type2Type<NewOroFix44MD::MDReqRejReason, char>(), "MDReqRejReason", 281, &NewOroFix44MD::realmbases[8] } },
   { 320, { Type2Type<NewOroFix44MD::InstrumentReqID>(), "InstrumentReqID", 320 } },
   { 371, { Type2Type<NewOroFix44MD::RefTagID>(), "RefTagID", 371 } },
   { 372, { Type2Type<NewOroFix44MD::RefMsgType>(), "RefMsgType", 372 } },
   { 373, { Type2Type<NewOroFix44MD::SessionRejectReason, int>(), "SessionRejectReason", 373, &NewOroFix44MD::realmbases[9] } },
   { 553, { Type2Type<NewOroFix44MD::Username>(), "Username", 553 } },
   { 559, { Type2Type<NewOroFix44MD::InstrumentListRequestType, int>(), "InstrumentListRequestType", 559, &NewOroFix44MD::realmbases[10] } },
   { 562, { Type2Type<NewOroFix44MD::MinTradeVol>(), "MinTradeVol", 562 } },
   { 893, { Type2Type<NewOroFix44MD::LastFragment, char>(), "LastFragment", 893, &NewOroFix44MD::realmbases[11] } },
   { 969, { Type2Type<NewOroFix44MD::MinPriceIncrement>(), "MinPriceIncrement", 969 } },
   { 1003, { Type2Type<NewOroFix44MD::TradeID>(), "TradeID", 1003 } },
   { 1140, { Type2Type<NewOroFix44MD::MaxTradeVol>(), "MaxTradeVol", 1140 } },
   { 2446, { Type2Type<NewOroFix44MD::AggressorSide, char>(), "AggressorSide", 2446, &NewOroFix44MD::realmbases[12] } },
   { 6136, { Type2Type<NewOroFix44MD::ReqID>(), "ReqID", 6136 } },
   { 25000, { Type2Type<NewOroFix44MD::RecvWindow>(), "RecvWindow", 25000 } },
   { 25003, { Type2Type<NewOroFix44MD::NoLimitIndicators>(), "NoLimitIndicators", 25003 } },
   { 25004, { Type2Type<NewOroFix44MD::LimitType, char>(), "LimitType", 25004, &NewOroFix44MD::realmbases[13] } },
   { 25005, { Type2Type<NewOroFix44MD::LimitCount>(), "LimitCount", 25005 } },
   { 25006, { Type2Type<NewOroFix44MD::LimitMax>(), "LimitMax", 25006 } },
   { 25007, { Type2Type<NewOroFix44MD::LimitResetInterval>(), "LimitResetInterval", 25007 } },
   { 25008, { Type2Type<NewOroFix44MD::LimitResetIntervalResolution, char>(), "LimitResetIntervalResolution", 25008, &NewOroFix44MD::realmbases[14] } },
   { 25016, { Type2Type<NewOroFix44MD::ErrorCode>(), "ErrorCode", 25016 } },
   { 25035, { Type2Type<NewOroFix44MD::MessageHandling, int>(), "MessageHandling", 25035, &NewOroFix44MD::realmbases[15] } },
   { 25037, { Type2Type<NewOroFix44MD::UUID>(), "UUID", 25037 } },
   { 25039, { Type2Type<NewOroFix44MD::MinQtyIncrement>(), "MinQtyIncrement", 25039 } },
   { 25040, { Type2Type<NewOroFix44MD::MarketMinTradeVol>(), "MarketMinTradeVol", 25040 } },
   { 25041, { Type2Type<NewOroFix44MD::MarketMaxTradeVol>(), "MarketMaxTradeVol", 25041 } },
   { 25042, { Type2Type<NewOroFix44MD::MarketMinQtyIncrement>(), "MarketMinQtyIncrement", 25042 } },
   { 25043, { Type2Type<NewOroFix44MD::FirstBookUpdateID>(), "FirstBookUpdateID", 25043 } },
   { 25044, { Type2Type<NewOroFix44MD::LastBookUpdateID>(), "LastBookUpdateID", 25044 } }
}; // 61
} // namespace NewOroFix44MD

} // namespace FIX8
