//-------------------------------------------------------------------------------------------------
// *** f8c generated file: DO NOT EDIT! Created: 2025-07-26 15:49:19 ***
//-------------------------------------------------------------------------------------------------
/*

Fix8 is released under the GNU LESSER GENERAL PUBLIC LICENSE Version 3.

Fix8 Open Source FIX Engine.
Copyright (C) 2010-25 David L. Dight <fix@fix8.org>

Fix8 is free software: you can  redistribute it and / or modify  it under the  terms of the
GNU Lesser General  Public License as  published  by the Free  Software Foundation,  either
version 3 of the License, or (at your option) any later version.

Fix8 is distributed in the hope  that it will be useful, but WITHOUT ANY WARRANTY;  without
even the  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

You should  have received a copy of the GNU Lesser General Public  License along with Fix8.
If not, see <http://www.gnu.org/licenses/>.

*******************************************************************************************
*                Special note for Fix8 compiler generated source code                     *
*                                                                                         *
* Binary works  that are the results of compilation of code that is generated by the Fix8 *
* compiler  can be released  without releasing your  source code as  long as your  binary *
* links dynamically  against an  unmodified version of the Fix8 library.  You are however *
* required to leave the copyright text in the generated code.                             *
*                                                                                         *
*******************************************************************************************

BECAUSE THE PROGRAM IS  LICENSED FREE OF  CHARGE, THERE IS NO  WARRANTY FOR THE PROGRAM, TO
THE EXTENT  PERMITTED  BY  APPLICABLE  LAW.  EXCEPT WHEN  OTHERWISE  STATED IN  WRITING THE
COPYRIGHT HOLDERS AND/OR OTHER PARTIES  PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY OF ANY
KIND,  EITHER EXPRESSED   OR   IMPLIED,  INCLUDING,  BUT   NOT  LIMITED   TO,  THE  IMPLIED
WARRANTIES  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS TO
THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE,
YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

IN NO EVENT UNLESS REQUIRED  BY APPLICABLE LAW  OR AGREED TO IN  WRITING WILL ANY COPYRIGHT
HOLDER, OR  ANY OTHER PARTY  WHO MAY MODIFY  AND/OR REDISTRIBUTE  THE PROGRAM AS  PERMITTED
ABOVE,  BE  LIABLE  TO  YOU  FOR  DAMAGES,  INCLUDING  ANY  GENERAL, SPECIAL, INCIDENTAL OR
CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT
NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR
THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH
HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

*/

//-------------------------------------------------------------------------------------------------
#include <fix8/f8config.h>
#if defined FIX8_MAGIC_NUM && FIX8_MAGIC_NUM > 16793603L
#error NewOroFix44OE_types.hpp version 1.4.3 is out of date. Please regenerate with f8c.
#endif
//-------------------------------------------------------------------------------------------------
// NewOroFix44OE_types.hpp
//-------------------------------------------------------------------------------------------------
#ifndef FIX8_4E65774F726F46697834344F455F74797065732E687070_
#define FIX8_4E65774F726F46697834344F455F74797065732E687070_

namespace FIX8 {
namespace NewOroFix44OE {

//-------------------------------------------------------------------------------------------------
using BeginString = Field<f8String, 8>;
const f8String BeginString_FIX44("FIX.4.4");
const size_t BeginString_realm_els(1);
//-------------------------------------------------------------------------------------------------
using BodyLength = Field<Length, 9>;
//-------------------------------------------------------------------------------------------------
using CheckSum = Field<f8String, 10>;
//-------------------------------------------------------------------------------------------------
using ClOrdID = Field<f8String, 11>;
//-------------------------------------------------------------------------------------------------
using CumQty = Field<Qty, 14>;
//-------------------------------------------------------------------------------------------------
using ExecID = Field<int, 17>;
//-------------------------------------------------------------------------------------------------
using ExecInst = Field<char, 18>;
const char ExecInst_PARTICIPATE_DONT_INITIATE('6');
const size_t ExecInst_realm_els(1);
//-------------------------------------------------------------------------------------------------
using LastPx = Field<price, 31>;
//-------------------------------------------------------------------------------------------------
using LastQty = Field<Qty, 32>;
//-------------------------------------------------------------------------------------------------
using MsgSeqNum = Field<SeqNum, 34>;
//-------------------------------------------------------------------------------------------------
using MsgType = Field<f8String, 35>;
const f8String MsgType_HEARTBEAT("0");
const f8String MsgType_TEST_REQUEST("1");
const f8String MsgType_REJECT("3");
const f8String MsgType_LOGOUT("5");
const f8String MsgType_EXECUTION_REPORT("8");
const f8String MsgType_ORDER_CANCEL_REJECT("9");
const f8String MsgType_LOGON("A");
const f8String MsgType_NEWS("B");
const f8String MsgType_NEW_ORDER_SINGLE("D");
const f8String MsgType_NEW_ORDER_LIST("E");
const f8String MsgType_ORDER_CANCEL_REQUEST("F");
const f8String MsgType_LIST_STATUS("N");
const f8String MsgType_ORDER_AMEND_KEEP_PRIORITY_REQUEST("XAK");
const f8String MsgType_ORDER_AMEND_REJECT("XAR");
const f8String MsgType_ORDER_CANCEL_REQUEST_AND_NEW_ORDER_SINGLE("XCN");
const f8String MsgType_LIMIT_QUERY("XLQ");
const f8String MsgType_LIMIT_RESPONSE("XLR");
const f8String MsgType_ORDER_MASS_CANCEL_REQUEST("q");
const f8String MsgType_ORDER_MASS_CANCEL_REPORT("r");
const size_t MsgType_realm_els(19);
//-------------------------------------------------------------------------------------------------
using OrderID = Field<int, 37>;
//-------------------------------------------------------------------------------------------------
using OrderQty = Field<Qty, 38>;
//-------------------------------------------------------------------------------------------------
using OrdStatus = Field<char, 39>;
const char OrdStatus_NEW('0');
const char OrdStatus_PARTIALLY_FILLED('1');
const char OrdStatus_FILLED('2');
const char OrdStatus_CANCELED('4');
const char OrdStatus_PENDING_CANCEL('6');
const char OrdStatus_REJECTED('8');
const char OrdStatus_PENDING_NEW('A');
const char OrdStatus_EXPIRED('C');
const size_t OrdStatus_realm_els(8);
//-------------------------------------------------------------------------------------------------
using OrdType = Field<char, 40>;
const char OrdType_MARKET('1');
const char OrdType_LIMIT('2');
const char OrdType_STOP('3');
const char OrdType_STOP_LIMIT('4');
const size_t OrdType_realm_els(4);
//-------------------------------------------------------------------------------------------------
using OrigClOrdID = Field<f8String, 41>;
//-------------------------------------------------------------------------------------------------
using Price = Field<price, 44>;
//-------------------------------------------------------------------------------------------------
using RefSeqNum = Field<int, 45>;
//-------------------------------------------------------------------------------------------------
using SenderCompID = Field<f8String, 49>;
//-------------------------------------------------------------------------------------------------
using SendingTime = Field<UTCTimestamp, 52>;
//-------------------------------------------------------------------------------------------------
using Side = Field<char, 54>;
const char Side_BUY('1');
const char Side_SELL('2');
const size_t Side_realm_els(2);
//-------------------------------------------------------------------------------------------------
using Symbol = Field<f8String, 55>;
//-------------------------------------------------------------------------------------------------
using TargetCompID = Field<f8String, 56>;
//-------------------------------------------------------------------------------------------------
using Text = Field<f8String, 58>;
//-------------------------------------------------------------------------------------------------
using TimeInForce = Field<char, 59>;
const char TimeInForce_GOOD_TILL_CANCEL('1');
const char TimeInForce_IMMEDIATE_OR_CANCEL('3');
const char TimeInForce_FILL_OR_KILL('4');
const size_t TimeInForce_realm_els(3);
//-------------------------------------------------------------------------------------------------
using TransactTime = Field<UTCTimestamp, 60>;
//-------------------------------------------------------------------------------------------------
using ListID = Field<int, 66>;
//-------------------------------------------------------------------------------------------------
using AllocID = Field<int, 70>;
//-------------------------------------------------------------------------------------------------
using NoOrders = Field<NumInGroup, 73>;
//-------------------------------------------------------------------------------------------------
using RawDataLength = Field<Length, 95>;
//-------------------------------------------------------------------------------------------------
using RawData = Field<data, 96>;
//-------------------------------------------------------------------------------------------------
using EncryptMethod = Field<int, 98>;
const int EncryptMethod_NONE(0);
const size_t EncryptMethod_realm_els(1);
//-------------------------------------------------------------------------------------------------
using OrdRejReason = Field<int, 103>;
const int OrdRejReason_OTHER(99);
const size_t OrdRejReason_realm_els(1);
//-------------------------------------------------------------------------------------------------
using HeartBtInt = Field<int, 108>;
//-------------------------------------------------------------------------------------------------
using MaxFloor = Field<Qty, 111>;
//-------------------------------------------------------------------------------------------------
using TestReqID = Field<f8String, 112>;
//-------------------------------------------------------------------------------------------------
using NoMiscFees = Field<NumInGroup, 136>;
//-------------------------------------------------------------------------------------------------
using MiscFeeAmt = Field<Qty, 137>;
//-------------------------------------------------------------------------------------------------
using MiscFeeCurr = Field<f8String, 138>;
//-------------------------------------------------------------------------------------------------
using MiscFeeType = Field<int, 139>;
const int MiscFeeType_EXCHANGE_FEES(4);
const size_t MiscFeeType_realm_els(1);
//-------------------------------------------------------------------------------------------------
using ResetSeqNumFlag = Field<Boolean, 141>;
const char ResetSeqNumFlag_NO('N');
const char ResetSeqNumFlag_YES('Y');
const size_t ResetSeqNumFlag_realm_els(2);
//-------------------------------------------------------------------------------------------------
using Headline = Field<f8String, 148>;
//-------------------------------------------------------------------------------------------------
using ExecType = Field<char, 150>;
const char ExecType_NEW('0');
const char ExecType_CANCELED('4');
const char ExecType_REPLACED('5');
const char ExecType_REJECTED('8');
const char ExecType_EXPIRED('C');
const char ExecType_TRADE('F');
const size_t ExecType_realm_els(6);
//-------------------------------------------------------------------------------------------------
using LeavesQty = Field<Qty, 151>;
//-------------------------------------------------------------------------------------------------
using CashOrderQty = Field<Qty, 152>;
//-------------------------------------------------------------------------------------------------
using RefTagID = Field<int, 371>;
//-------------------------------------------------------------------------------------------------
using RefMsgType = Field<f8String, 372>;
//-------------------------------------------------------------------------------------------------
using SessionRejectReason = Field<int, 373>;
const int SessionRejectReason_INVALID_TAG_NUMBER(0);
const int SessionRejectReason_REQUIRED_TAG_MISSING(1);
const int SessionRejectReason_TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE(2);
const int SessionRejectReason_UNDEFINED_TAG(3);
const int SessionRejectReason_VALUE_IS_INCORRECT(5);
const int SessionRejectReason_INCORRECT_DATA_FORMAT_FOR_VALUE(6);
const int SessionRejectReason_SIGNATURE_PROBLEM(8);
const int SessionRejectReason_SENDINGTIME_ACCURACY_PROBLEM(10);
const int SessionRejectReason_TAG_APPEARS_MORE_THAN_ONCE(13);
const int SessionRejectReason_TAG_SPECIFIED_OUT_OF_REQUIRED_ORDER(14);
const int SessionRejectReason_REPEATING_GROUP_FIELDS_OUT_OF_ORDER(15);
const int SessionRejectReason_INCORRECT_NUMINGROUP_COUNT_FOR_REPEATING_GROUP(16);
const int SessionRejectReason_OTHER(99);
const size_t SessionRejectReason_realm_els(13);
//-------------------------------------------------------------------------------------------------
using ListStatusType = Field<int, 429>;
const int ListStatusType_RESPONSE(2);
const int ListStatusType_EXEC_STARTED(4);
const int ListStatusType_ALL_DONE(5);
const int ListStatusType_UPDATED(100);
const size_t ListStatusType_realm_els(4);
//-------------------------------------------------------------------------------------------------
using ListOrderStatus = Field<int, 431>;
const int ListOrderStatus_EXECUTING(3);
const int ListOrderStatus_ALL_DONE(6);
const int ListOrderStatus_REJECT(7);
const size_t ListOrderStatus_realm_els(3);
//-------------------------------------------------------------------------------------------------
using CxlRejResponseTo = Field<char, 434>;
const char CxlRejResponseTo_ORDER_CANCEL_REQUEST('1');
const size_t CxlRejResponseTo_realm_els(1);
//-------------------------------------------------------------------------------------------------
using MassCancelRequestType = Field<char, 530>;
const char MassCancelRequestType_CANCEL_SYMBOL_ORDERS('1');
const size_t MassCancelRequestType_realm_els(1);
//-------------------------------------------------------------------------------------------------
using MassCancelResponse = Field<char, 531>;
const char MassCancelResponse_CANCEL_REQUEST_REJECTED('0');
const char MassCancelResponse_CANCEL_SYMBOL_ORDERS('1');
const size_t MassCancelResponse_realm_els(2);
//-------------------------------------------------------------------------------------------------
using MassCancelRejectReason = Field<int, 532>;
const int MassCancelRejectReason_OTHER(99);
const size_t MassCancelRejectReason_realm_els(1);
//-------------------------------------------------------------------------------------------------
using TotalAffectedOrders = Field<int, 533>;
//-------------------------------------------------------------------------------------------------
using Username = Field<f8String, 553>;
//-------------------------------------------------------------------------------------------------
using MatchType = Field<f8String, 574>;
const f8String MatchType_ONE_PARTY_TRADE_REPORT("1");
const f8String MatchType_AUTO_MATCH("4");
const size_t MatchType_realm_els(2);
//-------------------------------------------------------------------------------------------------
using WorkingIndicator = Field<Boolean, 636>;
//-------------------------------------------------------------------------------------------------
using TargetStrategy = Field<int, 847>;
//-------------------------------------------------------------------------------------------------
using TradeID = Field<int, 1003>;
//-------------------------------------------------------------------------------------------------
using AggressorIndicator = Field<Boolean, 1057>;
const char AggressorIndicator_ORDER_INITIATOR_IS_PASSIVE('N');
const char AggressorIndicator_ORDER_INITIATOR_IS_AGGRESSOR('Y');
const size_t AggressorIndicator_realm_els(2);
//-------------------------------------------------------------------------------------------------
using TriggerType = Field<char, 1100>;
const char TriggerType_PRICE_MOVEMENT('4');
const size_t TriggerType_realm_els(1);
//-------------------------------------------------------------------------------------------------
using TriggerAction = Field<char, 1101>;
const char TriggerAction_ACTIVATE('1');
const size_t TriggerAction_realm_els(1);
//-------------------------------------------------------------------------------------------------
using TriggerPrice = Field<price, 1102>;
//-------------------------------------------------------------------------------------------------
using TriggerPriceType = Field<char, 1107>;
const char TriggerPriceType_LAST_TRADE('2');
const size_t TriggerPriceType_realm_els(1);
//-------------------------------------------------------------------------------------------------
using TriggerPriceDirection = Field<char, 1109>;
const char TriggerPriceDirection_TRIGGER_IF_THE_PRICE_OF_THE_SPECIFIED_TYPE_GOES_DOWN_TO_OR_THROUGH_THE_SPECIFIED_TRIGGER_PRICE('D');
const char TriggerPriceDirection_TRIGGER_IF_THE_PRICE_OF_THE_SPECIFIED_TYPE_GOES_UP_TO_OR_THROUGH_THE_SPECIFIED_TRIGGER_PRICE('U');
const size_t TriggerPriceDirection_realm_els(2);
//-------------------------------------------------------------------------------------------------
using ContingencyType = Field<int, 1385>;
const int ContingencyType_ONE_CANCELS_THE_OTHER(1);
const int ContingencyType_ONE_TRIGGERS_THE_OTHER(2);
const size_t ContingencyType_realm_els(2);
//-------------------------------------------------------------------------------------------------
using ListRejectReason = Field<int, 1386>;
const int ListRejectReason_OTHER(99);
const size_t ListRejectReason_realm_els(1);
//-------------------------------------------------------------------------------------------------
using ReqID = Field<f8String, 6136>;
//-------------------------------------------------------------------------------------------------
using StrategyID = Field<int, 7940>;
//-------------------------------------------------------------------------------------------------
using DropCopyFlag = Field<Boolean, 9406>;
//-------------------------------------------------------------------------------------------------
using RecvWindow = Field<int, 25000>;
//-------------------------------------------------------------------------------------------------
using SelfTradePreventionMode = Field<char, 25001>;
const char SelfTradePreventionMode_NONE('1');
const char SelfTradePreventionMode_EXPIRE_TAKER('2');
const char SelfTradePreventionMode_EXPIRE_MAKER('3');
const char SelfTradePreventionMode_EXPIRE_BOTH('4');
const char SelfTradePreventionMode_DECREMENT('5');
const size_t SelfTradePreventionMode_realm_els(5);
//-------------------------------------------------------------------------------------------------
using CancelRestrictions = Field<int, 25002>;
const int CancelRestrictions_ONLY_NEW(1);
const int CancelRestrictions_ONLY_PARTIALLY_FILLED(2);
const size_t CancelRestrictions_realm_els(2);
//-------------------------------------------------------------------------------------------------
using NoLimitIndicators = Field<NumInGroup, 25003>;
//-------------------------------------------------------------------------------------------------
using LimitType = Field<char, 25004>;
const char LimitType_ORDER_LIMIT('1');
const char LimitType_MESSAGE_LIMIT('2');
const size_t LimitType_realm_els(2);
//-------------------------------------------------------------------------------------------------
using LimitCount = Field<int, 25005>;
//-------------------------------------------------------------------------------------------------
using LimitMax = Field<int, 25006>;
//-------------------------------------------------------------------------------------------------
using LimitResetInterval = Field<int, 25007>;
//-------------------------------------------------------------------------------------------------
using LimitResetIntervalResolution = Field<char, 25008>;
const char LimitResetIntervalResolution_DAY('d');
const char LimitResetIntervalResolution_HOUR('h');
const char LimitResetIntervalResolution_MINUTE('m');
const char LimitResetIntervalResolution_SECOND('s');
const size_t LimitResetIntervalResolution_realm_els(4);
//-------------------------------------------------------------------------------------------------
using TriggerTrailingDeltaBips = Field<int, 25009>;
//-------------------------------------------------------------------------------------------------
using NoListTriggeringInstructions = Field<NumInGroup, 25010>;
//-------------------------------------------------------------------------------------------------
using ListTriggerType = Field<char, 25011>;
const char ListTriggerType_ACTIVATED('1');
const char ListTriggerType_PARTIALLY_FILLED('2');
const char ListTriggerType_FILLED('3');
const size_t ListTriggerType_realm_els(3);
//-------------------------------------------------------------------------------------------------
using ListTriggerTriggerIndex = Field<int, 25012>;
//-------------------------------------------------------------------------------------------------
using ListTriggerAction = Field<char, 25013>;
const char ListTriggerAction_RELEASE('1');
const char ListTriggerAction_CANCEL('2');
const size_t ListTriggerAction_realm_els(2);
//-------------------------------------------------------------------------------------------------
using ClListID = Field<f8String, 25014>;
//-------------------------------------------------------------------------------------------------
using OrigClListID = Field<f8String, 25015>;
//-------------------------------------------------------------------------------------------------
using ErrorCode = Field<int, 25016>;
//-------------------------------------------------------------------------------------------------
using CumQuoteQty = Field<Qty, 25017>;
//-------------------------------------------------------------------------------------------------
using OrderCreationTime = Field<UTCTimestamp, 25018>;
//-------------------------------------------------------------------------------------------------
using WorkingFloor = Field<int, 25021>;
const int WorkingFloor_EXCHANGE(1);
const int WorkingFloor_BROKER(2);
const int WorkingFloor_SOR(3);
const size_t WorkingFloor_realm_els(3);
//-------------------------------------------------------------------------------------------------
using TrailingTime = Field<UTCTimestamp, 25022>;
//-------------------------------------------------------------------------------------------------
using WorkingTime = Field<UTCTimestamp, 25023>;
//-------------------------------------------------------------------------------------------------
using PreventedMatchID = Field<int, 25024>;
//-------------------------------------------------------------------------------------------------
using PreventedExecutionPrice = Field<price, 25025>;
//-------------------------------------------------------------------------------------------------
using PreventedExecutionQty = Field<Qty, 25026>;
//-------------------------------------------------------------------------------------------------
using TradeGroupID = Field<int, 25027>;
//-------------------------------------------------------------------------------------------------
using CounterSymbol = Field<f8String, 25028>;
//-------------------------------------------------------------------------------------------------
using CounterOrderID = Field<int, 25029>;
//-------------------------------------------------------------------------------------------------
using PreventedQty = Field<Qty, 25030>;
//-------------------------------------------------------------------------------------------------
using LastPreventedQty = Field<Qty, 25031>;
//-------------------------------------------------------------------------------------------------
using SOR = Field<Boolean, 25032>;
//-------------------------------------------------------------------------------------------------
using OrderCancelRequestAndNewOrderSingleMode = Field<int, 25033>;
const int OrderCancelRequestAndNewOrderSingleMode_STOP_ON_FAILURE(1);
const int OrderCancelRequestAndNewOrderSingleMode_ALLOW_FAILURE(2);
const size_t OrderCancelRequestAndNewOrderSingleMode_realm_els(2);
//-------------------------------------------------------------------------------------------------
using CancelClOrdID = Field<f8String, 25034>;
//-------------------------------------------------------------------------------------------------
using MessageHandling = Field<int, 25035>;
const int MessageHandling_UNORDERED(1);
const int MessageHandling_SEQUENTIAL(2);
const size_t MessageHandling_realm_els(2);
//-------------------------------------------------------------------------------------------------
using ResponseMode = Field<int, 25036>;
const int ResponseMode_EVERYTHING(1);
const int ResponseMode_ONLY_ACKS(2);
const size_t ResponseMode_realm_els(2);
//-------------------------------------------------------------------------------------------------
using UUID = Field<f8String, 25037>;
//-------------------------------------------------------------------------------------------------
using OrderRateLimitExceededMode = Field<int, 25038>;
const int OrderRateLimitExceededMode_DO_NOTHING(1);
const int OrderRateLimitExceededMode_CANCEL_ONLY(2);
const size_t OrderRateLimitExceededMode_realm_els(2);
//-------------------------------------------------------------------------------------------------
using NewOroFix44OE_BaseEntry = FieldTable;

} // namespace NewOroFix44OE
} // namespace FIX8
#endif // FIX8_4E65774F726F46697834344F455F74797065732E687070_
