include(FetchContent)

set(LWS_WITH_SSL           ON CACHE BOOL "" FORCE)
set(LWS_WITH_MBEDTLS       OFF  CACHE BOOL "" FORCE)
set(LWS_WITHOUT_EXTENSIONS ON  CACHE BOOL "" FORCE)

set(LWS_WITH_STATIC        ON  CACHE BOOL "" FORCE)
set(LWS_WITH_SHARED        OFF CACHE BOOL "" FORCE)

set(LWS_WITHOUT_TESTAPPS   ON  CACHE BOOL "" FORCE)
set(LWS_WITHOUT_TEST_SERVER ON CACHE BOOL "" FORCE)
set(LWS_WITHOUT_TEST_PING  ON  CACHE BOOL "" FORCE)
set(LWS_WITHOUT_TEST_CLIENT ON CACHE BOOL "" FORCE)
set(LWS_WITHOUT_SERVER     ON  CACHE BOOL "" FORCE)

set(LWS_WITH_CLIENT        ON  CACHE BOOL "" FORCE)
set(LWS_WITH_SERVER        OFF CACHE BOOL "" FORCE)

set(LWS_WITH_HTTP2         OFF CACHE BOOL "" FORCE)
set(LWS_WITH_LIBUV         OFF CACHE BOOL "" FORCE)
set(LWS_WITH_LIBEVENT      OFF CACHE BOOL "" FORCE)
set(LWS_WITH_LIBEV         OFF CACHE BOOL "" FORCE)
set(LWS_WITH_GLIB          OFF CACHE BOOL "" FORCE)

set(LWS_WITH_ZLIB          OFF CACHE BOOL "" FORCE)
set(LWS_WITH_MINIZ         OFF CACHE BOOL "" FORCE)

set(LWS_IPV6               OFF CACHE BOOL "" FORCE)
set(LWS_UNIX_SOCK          OFF CACHE BOOL "" FORCE)

set(LWS_WITH_ZIP_FOPS      OFF CACHE BOOL "" FORCE)
set(LWS_WITH_SOCKS5        OFF CACHE BOOL "" FORCE)
set(LWS_WITH_GENERIC_SESSIONS OFF CACHE BOOL "" FORCE)
set(LWS_WITH_ACCESS_LOG    OFF CACHE BOOL "" FORCE)
set(LWS_WITH_RANGES        OFF CACHE BOOL "" FORCE)
set(LWS_WITH_CGI           OFF CACHE BOOL "" FORCE)
set(LWS_WITH_HTTP_PROXY    OFF CACHE BOOL "" FORCE)
set(LWS_WITH_HTTP_STREAM_COMPRESSION OFF CACHE BOOL "" FORCE)

set(LWS_WITH_MINIMAL_EXAMPLES OFF CACHE BOOL "" FORCE)

set(LWS_WITHOUT_BUILTIN_GETIFADDRS ON CACHE BOOL "" FORCE)
set(LWS_WITHOUT_BUILTIN_SHA1       ON CACHE BOOL "" FORCE)

set(LWS_WITH_LEJP         ON  CACHE BOOL "" FORCE)
set(LWS_WITH_STRUCT_JSON  OFF CACHE BOOL "" FORCE)
set(LWS_WITH_STRUCT_SQLITE3 OFF CACHE BOOL "" FORCE)

set(LWS_WITH_JOSE         OFF CACHE BOOL "" FORCE)
set(LWS_WITH_GENCRYPTO    OFF CACHE BOOL "" FORCE)
set(LWS_WITH_CUSTOM_HEADERS OFF CACHE BOOL "" FORCE)

set(LWS_WITH_THREADPOOL   OFF CACHE BOOL "" FORCE)
set(LWS_WITH_PLUGINS      OFF CACHE BOOL "" FORCE)
set(LWS_WITH_PLUGINS_BUILTIN OFF CACHE BOOL "" FORCE)

set(LWS_WITH_FILE_OPS     ON  CACHE BOOL "" FORCE)
set(LWS_WITH_STATS        OFF CACHE BOOL "" FORCE)
set(LWS_WITH_PEER_LIMITS  OFF CACHE BOOL "" FORCE)

set(LWS_WITH_LIBCAP       OFF CACHE BOOL "" FORCE)

set(LWS_SUPPRESS_DEPRECATED_API_WARNINGS ON CACHE BOOL "" FORCE)
set(LWS_WITH_DEPRECATED_LWS_DLL OFF CACHE BOOL "" FORCE)

FetchContent_Declare(
    libwebsockets
    GIT_REPOSITORY https://github.com/warmcat/libwebsockets.git
    GIT_TAG        v4.4.0
    GIT_SHALLOW    TRUE
)

FetchContent_MakeAvailable(libwebsockets)

if(TARGET websockets)
    target_compile_options(websockets PRIVATE
        -Wno-error=unused-parameter
        -Wno-error=unused-label
    )
endif()
